### ISSUE TITLE
关于更新ubisoft规则的建议

### ISSUE THREAD

**Issue by JinjerTK** [v2fly/domain-list-community#1000]
dmx.upc.ubisoft.com
public-ubiservices.ubi.com

这两条规则可以加入@cn设置为直连，这样国内用户每次登录可以免去重复输入账号密码

**Comment by database64128** [comment]
These domains have no access points in China, and are therefore not eligible for the `cn` tag.

If you want specific routing behaviors, change your own routing rules.
