### ISSUE TITLE
domain rules set

### ISSUE THREAD

**Issue by usalaw91** [v2fly/domain-list-community#1007]
I want to bypass All subdomain before domain :-  cloudfront.net
Example -   **server-108-157-4-50.dus51.r.cloudfront.net**

I put below rules but does not work.

full:cloudfront.net
domain:cloudfront.net
plain string - cloudfront.net

which domain rules bypass above related domain?

**Comment by rootmelo92118** [comment]
I think you can try to use `domain:cloudfront.net`. It can match all subdomains base on `cloudfront.com` and use freedom protocol to connect to the server directly.
