### ISSUE TITLE
请问访问apple.com.cn为什么在两种geosite文件中不一样

### ISSUE THREAD

**Issue by GeorgeRudd** [v2fly/domain-list-community#1010]
客户端配置
```json
	"routing": {
		"domainStrategy": "IPIfNonMatch",
		"domainMatcher": "mph",
		"rules": [
			{
				"type": "field",
				"outboundTag": "proxy",
				"domains": [
					"geosite:geolocation-!cn"
				]
			},
			{
				"outboundTag": "direct",
				"type": "field",
				"domains": [
					"geosite:cn"
				]
			},
			{
				"outboundTag": "direct",
				"type": "field",
				"ip": [
					"geoip:cn",
					"geoip:private"
				]
			}
		]
	}
```
使用本项目的dlc.dat则走代理

而使用这里的geosite.dat则直连https://github.com/Loyalsoldier/v2ray-rules-dat/releases

**Comment by rootmelo92118** [comment]
`apple.com.cn` 在 `dlc.dat` 中的 `geolocation-!cn` -> `category-companies` -> `apple` 
而在[https://github.com/Loyalsoldier/v2ray-rules-dat](https://github.com/Loyalsoldier/v2ray-rules-dat/releases)的版本中，其引用了另一個倉庫[https://github.com/Loyalsoldier/domain-list-custom](https://github.com/Loyalsoldier/domain-list-custom)，其介紹中有特別提到與此版本不同之處
<img width="1440" alt="截圖 2022-07-16 下午11 31 35" src="https://user-images.githubusercontent.com/32770959/179361480-d169e564-a0dc-4feb-95f9-2ede7f0f6fae.png">
而`apple.com.cn` 後帶有 `@cn` 的後綴，其又被包含在`geolocation-!cn`中，所以該域名被刪除，其規則命中於你`Outbound`中第一個出站協議（依照你的形容應該是freedom） 也就直接出站。

而`dlc.dat`並沒有去做特別剔除域名的操作，所以 `apple.com.cn` 依然被包含在 `geolocation-!cn` 中，其域名命中於 `routing` -> `rules` 中的第一條規則，也就是代理。

**Comment by rootmelo92118** [comment]
那該問題應該是解決了吧
