### ISSUE TITLE
国内搜题软件域名未收录，以及作业帮域名未设置到cn分组

### ISSUE THREAD

**Issue by fengguowudi** [v2fly/domain-list-community#1070]
kuaiduizuoye.com

**Comment by fengguowudi** [comment]
快对作业的域名

**Comment by IceCodeNew** [comment]
你可以自己提交 PR 吗？

**Comment by rootmelo92118** [comment]
作業幫已經被`baidu`分類加入`geolocation-cn`中

**Comment by fengguowudi** [comment]
额。我没看懂这个该咋写啊QAQ。

**Comment by rootmelo92118** [comment]
> 额。我没看懂这个该咋写啊QAQ。

將其加入到`geolocation-cn`中即可，如果可以的話在裡面新增一個類別。
e.g.
```
# 快对作业的域名
kuaiduizuoye.com
```
記得還要按照字母排序將其放映在相對應的位置。

**Comment by fengguowudi** [comment]
okok

**Comment by fengguowudi** [comment]
> 作業幫已經被`baidu`分類加入`geolocation-cn`中

这个是说`include:baidu`这个类别对应的是data文件夹中baidu文件，而这个文件中包含了作业帮域名是吗？

**Comment by rootmelo92118** [comment]
> > 作業幫已經被`baidu`分類加入`geolocation-cn`中
> 
> 这个是说`include:baidu`这个类别对应的是data文件夹中baidu文件，而这个文件中包含了作业帮域名是吗？

是

**Comment by IceCodeNew** [comment]
fixed by #1075
