### ISSUE TITLE
googleapis 无法进行正确代理

### ISSUE THREAD

**Issue by bitxx** [v2fly/domain-list-community#1072]
这将导致 chrome 无法正确使用 google 的翻译功能

日志显示
2022/08/11 12:56:10 127.0.0.1:49465 accepted //translate.googleapis.com:443 [http -> direct]
2022/08/11 12:56:10 127.0.0.1:49462 accepted //translate.googleapis.com:443 [http -> direct]
2022/08/11 12:56:10 127.0.0.1:49461 accepted //translate.googleapis.com:443 [http -> direct]
2022/08/11 12:56:10 127.0.0.1:49463 accepted //translate.googleapis.com:443 [http -> direct]
2022/08/11 12:56:10 127.0.0.1:49460 accepted //translate.googleapis.com:443 [http -> direct]

**Comment by rootmelo92118** [comment]
這邊建議您可以將以下配置新增至
```
{
                "outboundTag": "代理標籤",
                "domain": [
                    "geosite:google"
                ],
                "type": "field"
            },
```
放置於國內直連之前

**Comment by IceCodeNew** [comment]
> 这将导致 chrome 无法正确使用 google 的翻译功能
> 
> 日志显示 2022/08/11 12:56:10 127.0.0.1:49465 accepted //translate.googleapis.com:443 [http -> direct] 2022/08/11 12:56:10 127.0.0.1:49462 accepted //translate.googleapis.com:443 [http -> direct] 2022/08/11 12:56:10 127.0.0.1:49461 accepted //translate.googleapis.com:443 [http -> direct] 2022/08/11 12:56:10 127.0.0.1:49463 accepted //translate.googleapis.com:443 [http -> direct] 2022/08/11 12:56:10 127.0.0.1:49460 accepted //translate.googleapis.com:443 [http -> direct]

<img width="396" alt="image" src="https://user-images.githubusercontent.com/32576256/184071687-541ea309-c47e-40ce-9067-09e29fb2f0c4.png">

和本项目无关，这个项目没有把 translate.googleapis.com 标注成国内域名

**Comment by rootmelo92118** [comment]
> > 这将导致 chrome 无法正确使用 google 的翻译功能
> > 日志显示 2022/08/11 12:56:10 127.0.0.1:49465 accepted //translate.googleapis.com:443 [http -> direct] 2022/08/11 12:56:10 127.0.0.1:49462 accepted //translate.googleapis.com:443 [http -> direct] 2022/08/11 12:56:10 127.0.0.1:49461 accepted //translate.googleapis.com:443 [http -> direct] 2022/08/11 12:56:10 127.0.0.1:49463 accepted //translate.googleapis.com:443 [http -> direct] 2022/08/11 12:56:10 127.0.0.1:49460 accepted //translate.googleapis.com:443 [http -> direct]
> 
> <img alt="image" width="396" src="https://user-images.githubusercontent.com/32576256/184071687-541ea309-c47e-40ce-9067-09e29fb2f0c4.png">
> 
> 和本项目无关，这个项目没有把 translate.googleapis.com 标注成国内域名
<img width="405" alt="截圖 2022-08-11 下午2 21 08" src="https://user-images.githubusercontent.com/32770959/184075247-8a916168-1a35-4232-aabd-1d262c3118bf.png">
其實有誒

**Comment by IceCodeNew** [comment]
> 其實有，但是依據解析結果似乎該域名在中國大陸並未被屏蔽。
> [result](https://www.boce.com/http/c29f08df740128ecb479b1e6350c5e4f.html)

一般被用作 direct 路由的分类就是 geosite:cn 大分类，这个分类的实际内容是可以在这个项目里查到的
https://github.com/v2fly/domain-list-community/blob/release/cn.txt

我在这个地方还是查不到 translate.google.com
