### ISSUE TITLE
合并如MVPS host等清单中列出的域名。

### ISSUE THREAD

**Issue by RealXuChe** [v2fly/domain-list-community#111]
诸如[MVPS host](http://winhelp2002.mvps.org/hosts.htm), [Dan Pollock's hosts](https://someonewhocares.org/hosts/)的项目，给出了非常详尽、丰富的广告/追踪/spam域名列表，建议合并到本项目。

因为这些域名列表包含了广告/追踪/spam域名，这些列表似乎不适合直接归入现有的分类。

我建议新开一个`general-ads-tracking-spam`分类或为每一个列表单独开一个同名的分类。

如果没有异议的话,我就提PR了.

**Comment by EpLiar** [comment]
广告域名应谨慎添加，毕竟大部分用户都是把广告直接进 blocked 的。因此如果要加，可以做了测试后再加。

同时这两个网站的许可证什么的也应注意，别的我就没什么意见。

**Comment by RealXuChe** [comment]
谢谢提醒,许可证问题的话,MVPS用的CC BY-NC-SA似乎与MIT不兼容,我会多加注意的.

请问"广告域名应谨慎添加"是什么意思?是指 "不应当将域名列表合并到`category-ads`里" 吗?

**Comment by IceCodeNew** [comment]
> 请问"广告域名应谨慎添加"是什么意思?是指 "不应当将域名列表合并到`category-ads`里" 吗?

联系上下文，他的意思应该是担心这些规则有误报。

**Comment by IceCodeNew** [comment]
我个人建议是你把这个 PR 提到 https://github.com/Loyalsoldier/v2ray-rules-dat 这边。
官方的 domain-list 不宜冒这么大的风险。

**Comment by EpLiar** [comment]
> 请问"广告域名应谨慎添加"是什么意思?是指 "不应当将域名列表合并到category-ads里" 吗?

广告域名被 include 到 category-ads-all 是没错的，但是要确定这是个广告域名。用户不会给你考虑域名的内容，他看到广告就会 ban 掉了。如果我们误收了非广告域名，就会影响用户的日常使用和工作。

**Comment by EpLiar** [comment]
广告域名是需要测试的，而且有些情况用户不一定认为是广告。

**Comment by RealXuChe** [comment]
好的, 我还是去 https://github.com/Loyalsoldier/v2ray-rules-dat 提吧.
