### ISSUE TITLE
Steam启动时新增访问 steamserver.net 域名

### ISSUE THREAD

**Issue by jam3ternal** [v2fly/domain-list-community#1125]
![image](https://user-images.githubusercontent.com/34647295/186834038-53a628d0-446c-49ab-9036-8732fdd8bcb4.png)
如图

**Comment by IceCodeNew** [comment]
截图不全，不采信。欢迎其他贡献者自己验证下这里的域名是否是 steam 官方所使用。

**Comment by rootmelo92118** [comment]
我剛剛針對steam客戶端進行抓包。我也發現了相關的域名，如下圖：
<img width="468" alt="截圖 2022-08-26 下午8 52 21" src="https://user-images.githubusercontent.com/32770959/186908481-6b17b853-3ac8-4a09-ae4f-086463b80b04.png">
我認為該域名可以被加入分類。

**Comment by wordlesswind** [comment]
https://ssl.steam.net/
https://ssl.steamserver.net/

https://crt.sh/?id=7111574902
![image](https://user-images.githubusercontent.com/9050713/187604136-41257350-ec9c-4bcc-8662-84b9c0df34f5.png)
