### ISSUE TITLE
some question about PR

### ISSUE THREAD

**Issue by MuenYu** [v2fly/domain-list-community#12]
I saw some files in `/data` that without any tag except domains

1. if i want to add some domain to here, should i do just like above? (just leave some domains in a file) 
2. if so, then you will classify them, right?
3. i'd like to work for this(domain collection), if the way above was wrong, show me the right way please!

thanks for every developer of this program, it's an excellent program.

**Comment by EpLiar** [comment]
In fact, we used to name a file by company/organization. The domain names belonging to this company/organization will be on file. After then, we will classify them into two main categories by geographic location:

* geolocation-cn
* geolocation-!cn

In `geolocation-!cn`, we categorize the companies/organizations to summarize. Such as `category-porn`, `category-media` etc.

**Comment by EpLiar** [comment]
After a few success pull requests, you can apply for manager access to this repository.

**Comment by Loyalsoldier** [comment]
There are three main parts(files) of the project: `geolocation-cn`, `geolocation-!cn` and `category-ads-all`. Almost each other file in the project is included into one of these three main files.

What you should do is to fork the repo, add domains of a brand/company/organization in `data` directory. Then `include:filename` into `geolocation-!cn` or `geolocation-cn` according to its geolocation. And of course, lists of domains that serve advertisement should be included into `category-ads-all`.

Finally, file a pull request, and wait for review.

**Comment by MuenYu** [comment]
OK, i see, thanks for your reply! @Loyalsoldier @EpLiar 

i will try my first PR soon.

by the way, i think you should add contents above into project's README, that would help some person who want to join.
