### ISSUE TITLE
`translation.googleapis.com` may not got cn IP

### ISSUE THREAD

**Issue by yin1999** [v2fly/domain-list-community#1224]
see: <https://ping.chinaz.com/translation.googleapis.com>

![image](https://user-images.githubusercontent.com/15844309/193196187-93d61995-bb16-4135-89b6-53bbdaeeae56.png)

**Comment by rootmelo92118** [comment]
I got a similar issue in the telegram group. I think the reason is the `20th National Congress of the Chinese Communist Party` will hold in Beijing. Maybe we can wait for it to end and make the decision whether this PR should be merged or not.

**Comment by database64128** [comment]
> Maybe we can wait for it to end and make the decision whether this issue should be fixed or not.

I don't think this is how it works. If it doesn't work, then it doesn't work and needs to be fixed.
