### ISSUE TITLE
最近发现安卓chrome 浏览器自带翻译不可用了

### ISSUE THREAD

**Issue by channingbox** [v2fly/domain-list-community#1234]
安卓平台chrome 浏览器自带的翻译不可用了

**Comment by KukiSa** [comment]
> 安卓平台chrome 浏览器自带的翻译不可用了

https://www.cnbc.com/2022/10/03/google-shuts-down-translate-service-in-china-.html

**Comment by channingbox** [comment]
目前翻译功能恢复了。
