### ISSUE TITLE
difference with Loyalsoldier/v2ray-rules-dat

### ISSUE THREAD

**Issue by hadifarnoud** [v2fly/domain-list-community#1298]
How is this different from [Loyalsoldier/v2ray-rules-dat](https://github.com/Loyalsoldier/v2ray-rules-dat)?

which one I should use?

**Comment by Loyalsoldier** [comment]
domain-list-community is one of the data sources of v2ray-rules-dat.

v2ray-rules-dat uses repo [domain-list-custom](https://github.com/Loyalsoldier/domain-list-custom) to build the `geosite.dat` with some modification described in [README](https://github.com/Loyalsoldier/domain-list-custom#%E4%B8%8E%E5%AE%98%E6%96%B9%E7%89%88-dlcdat-%E4%B8%8D%E5%90%8C%E4%B9%8B%E5%A4%84)
