### ISSUE TITLE
add category-tracker

### ISSUE THREAD

**Issue by Hubedge** [v2fly/domain-list-community#1306]
I'm aware of https://github.com/v2fly/domain-list-community/blob/master/data/category-pt but we lack a category for trackers.

https://github.com/ngosang/trackerslist would be a good starting point.

**Comment by IceCodeNew** [comment]
Naming the category as "category-tracking" could lead to misunderstanding.  
How about `category-public-tracker`?  
Also, PR is welcomed.  
  
**Please be aware that copying & pasting the third-party maintained list is not encouraged, doing so would bring the risk of syntax error and violating their license.**

**Comment by Hubedge** [comment]
`category-public-tracker` sounds good.

I will try to put together a PR from scratch.
