### ISSUE TITLE
请求向alibaba中添加AlipayHK相关域名

### ISSUE THREAD

**Issue by jam3ternal** [v2fly/domain-list-community#1310]
![E4AA26BA-D36C-4186-880C-270FFF975C3C](https://user-images.githubusercontent.com/34647295/201593241-ca34daac-42eb-4d0e-8bd9-2dcc13176d06.jpeg)
如图, Quantumult X 的网络活动日志显示AlipayHK应用程序访问alipay.hk域名；
另外, www.alipayhk.com 网址也属于AlipayHK。

**Comment by jam3ternal** [comment]
![EA18A084-53DE-42A6-B8D5-0C615DA80F4E](https://user-images.githubusercontent.com/34647295/201595107-f0c2fe58-78d0-450e-8734-1d589af06e22.jpeg)
另外Alipa澳门版会访问alipaymo.com域名

**Comment by IceCodeNew** [comment]
能尝试下自己提 PR 吗。

**Comment by jam3ternal** [comment]
> 能尝试下自己提 PR 吗。

好的，下次如果再发现缺少的域名我试一下自己提PR。
