### ISSUE TITLE
dyna 分类中 域名

### ISSUE THREAD

**Issue by PanHsin** [v2fly/domain-list-community#1312]
dynacw.com.cn , dynacw.com.hk,  dynacw.com.jp 网站  似乎不存在了。更新一下？
![image](https://user-images.githubusercontent.com/26317972/201705040-49216ebd-5464-471a-972b-02a194f4ac3f.png).

**Comment by IceCodeNew** [comment]
DNS 解析记录不存在不能作为移除域名的依据。
如果有因为这些域名导致问题，可以把原始问题放上来。
