### ISSUE TITLE
域名归类问题

### ISSUE THREAD

**Issue by kabegoe** [v2fly/domain-list-community#1317]
使用中国国内短视频应用时应用会访问这些域名，例如`sovv.yilanvaas.com`, `ovv.alllook.tv`。
请问一下放在哪个类别比较合适？且希望`geosite:cn`能对应到这些域名。

**Comment by rootmelo92118** [comment]
你是在使用哪一個應用的時候發現的？

**Comment by kabegoe** [comment]
确认了一下好像只是发送DNS请求，貌似并没有往解析到的ip地址发送TCP/UDP请求。可能是应用写的有问题吧。

**Comment by rootmelo92118** [comment]
那就暫且不更動吧
