### ISSUE TITLE
> 3. gfwlist 作为一个临时解决方案，不应该继续扩大影响力，这种方案应该逐渐被移除；

### ISSUE THREAD

**Issue by Sheng25201445** [v2fly/domain-list-community#1336]
> 3. gfwlist 作为一个临时解决方案，不应该继续扩大影响力，这种方案应该逐渐被移除；
> 4. 这会改变集合的定义，如果移除，那为什么不用一个新的诸如 geopop 这样的名字；

第四点没看懂什么意思

_Originally posted by @Loyalsoldier in https://github.com/v2fly/domain-list-community/issues/256#issuecomment-711559712_

**Comment by IceCodeNew** [comment]
你只是把别人说过的话全部复制粘贴上来而已，不知道你想表达什么。

**Comment by xiaorong61** [comment]
pop 有接入点的意思
