### ISSUE TITLE
能否将这两个域名后缀加入到能够直连的合集中。

### ISSUE THREAD

**Issue by lin1123** [v2fly/domain-list-community#1348]
添加后可以通过直连来更新play商店的应用。
https://github.com/SagerNet/SagerNet/issues/573#issuecomment-1315054851

**Comment by IceCodeNew** [comment]
1. 这个项目维护的原则是反映大多数用户网络场景下域名适合的分类，不是为了代理配置的方便。在发起域名分类的建议时需要提供证据，不能基于单独一位用户的汇报就下结论。
2. `googleapis.cn` 域名如果设置直连，我印象中也会影响 google play 服务的使用。正确的做法是将这个域名覆写为 `googleapis.com` 然后走代理。
3. 你链接的 issue 给的两个域名中，其中一个域名很奇怪（见以下截图）。我不觉得这个域名和 play 商店有什么关系。希望下次提建议之前先自己验证一遍，不要直接搬运不相关的信息进来。

<img width="317" alt="image" src="https://user-images.githubusercontent.com/32576256/205962913-b5fe6e5b-f52e-457d-b631-c643b1ebb082.png">

**Comment by lin1123** [comment]
xn--ngstr-lra8j.com
这个域名只是个后缀，通过play商店下载应用后，查找日志发现完整访问的域名为 rr3---sn-ni57rn7y.xn--ngstr-lra8j.com:443，显示的IP为360云服务器，实际访问为Google的网站，但是这个域名后缀被放在了Google的合集里面。
I/v2ray-core: [3267464819] proxy/http: request to Method [CONNECT] Host [rr2---sn-ni57rn7k.xn--ngstr-lra8j.com:443] with URL [//rr2---sn-ni57rn7k.xn--ngstr-lra8j.com:443]
D/v2ray-core: app/dispatcher: dispatch conn to tcp:rr2---sn-ni57rn7k.xn--ngstr-lra8j.com:443
I/v2ray-core: [3267464819] app/dispatcher: sniffed domain: rr2---sn-ni57rn7k.xn--ngstr-lra8j.com
I/v2ray-core: [3267464819] app/dispatcher: taking detour [bypass] for [tcp:rr2---sn-ni57rn7k.xn--ngstr-lra8j.com:443]
I/v2ray-core: [3267464819] proxy/freedom: opening connection to tcp:rr2---sn-ni57rn7k.xn--ngstr-lra8j.com:443
I/v2ray-core: [3267464819] transport/internet/tcp: dialing TCP to tcp:rr2---sn-ni57rn7k.xn--ngstr-lra8j.com:443
D/v2ray-core: 127.0.0.1:47138 accepted //rr2---sn-ni57rn7k.xn--ngstr-lra8j.com:443 [bypass]
D/v2ray-core: app/dns: domain rr2---sn-ni57rn7k.xn--ngstr-lra8j.com matches following rules: [[geosite:cn full:cloud.wlcloud.buzz full:dns.google domain:xn--ngstr-lra8j.com domain:googleapis.cn geosite:private](DNS idx:1)]

**Comment by IceCodeNew** [comment]
> 显示的IP为360云服务器，实际访问为Google的网站，但是这个域名后缀被放在了Google的合集里面。

谢谢回复，查了一下 `xn--ngstr-lra8j.com` 这个域名确实应该是 google 所有的域名。所以现在的分类是没问题的。显示 IP 为 xxx 这个信息，估计是很不准确的。

<img width="777" alt="image" src="https://user-images.githubusercontent.com/32576256/206122801-9b6cc21f-4ebb-49b2-855e-b01874b3d960.png">

---

然后参考下面这个 issue，该域名下的子域名存在不能直连的域名。所以不适合添加能够直连的属性标记。
https://github.com/gfwlist/gfwlist/issues/2255

（上面的信息可能过时或者存在错误。我没有时间进一步验证，你可以查过以后带着证据回来重新打开这个 issue）
