### ISSUE TITLE
青春北京 / 北京共青团 相关

### ISSUE THREAD

**Issue by zedifen** [v2fly/domain-list-community#1360]
共青团北京市委员会信息中心 (京ICP备14030447号-3):

- <code><strong>bjyouth</strong>.net</code>
- `bjyouth.gov.cn`
- `sqqnh.org`
- `sqqnh.cn`

北京尚古创新科技有限公司 (京ICP备14013186号):

- <code><strong>sumkoo</strong>.com</code>
- `sumkoo.cn`
- `sumkoo.net`
- `jzfz.net`
- `veeqi.net`
- <code><strong>wenmingban</strong>.com</code> ( "文明办" ? )
- <code><strong>gongqingyun</strong>.cn</code> ( "共青云" ? )
- `zhiyuanhe.cn`
- `zhiyuanyun.com.cn`
- `zyhe.com.cn`

知藏（北京）数据技术有限公司 (京ICP备19038827号):

- **`zzdtec.com`**

北京中青在线网络信息技术有限公司 (京ICP备16062000号):

- **`cyol.com`**

其它:

- `gtimg.cn` (深圳市腾讯计算机系统有限公司, 粤B2-20090059-17)
- `xinwen.cn` (新华网股份有限公司, 京ICP证010042号-2)
- **`webterren.com`** (北京天润基业科技发展股份有限公司, 京ICP备19052875号-1)
- `51.la` (广州有啦网络科技有限公司, 粤ICP备17055553号-1)

注: 每个主体下第一项为这次 "青年大学习" 时发现到的存在连接的域.

**Comment by rootmelo92118** [comment]
可以嘗試提交更改，如果覺得有困難畫可以發表你的意見。

**Comment by zedifen** [comment]
我不确定这些域名该放在哪些文件里 ? 如果有对应的文件, 该怎么找到 ? 如果没有的话, 是直接新建, 还是塞进 `cn` 里面 ?

**Comment by rootmelo92118** [comment]
> 我不确定这些域名该放在哪些文件里 ? 如果有对应的文件, 该怎么找到 ? 如果没有的话, 是直接新建, 还是塞进 `cn` 里面 ?

直接興建，並在完成後以`include`語法引入`geolocation-cn`中。
