### ISSUE TITLE
微软网络状态探测域名

### ISSUE THREAD

**Issue by kabegoe** [v2fly/domain-list-community#1386]
请问在#610 中，为什么`msftconnecttest.com`和`msftncsi.com`被添加到了`private`分类中，而不是`microsoft`分类？

**Comment by rootmelo92118** [comment]
https://github.com/Loyalsoldier/v2ray-rules-dat/issues/136
這或許能回答你的問題

**Comment by kabegoe** [comment]
在https://github.com/Loyalsoldier/v2ray-rules-dat/issues/136 中

> 建议microsoft分类添加：www.msftconnecttest.com 和 [www.msftncsi.com](http://www.msftncsi.com/)

作者也是建议添加到`microsoft`分类吧。

> 这两个是微软探测是否成功连接到网络的域名，详见：https://docs.microsoft.com/en-US/troubleshoot/windows-client/networking/internet-explorer-edge-open-connect-corporate-public-network

我也读了一下文档，windows需要解析或连接`www.msftconnecttest.com`, `www.msftncsi.com`, `dns.msftncsi.com`这三个域名来确认网络状态。而这三个域名的A记录对应的都是公网IP。

有什么资料说明这些域名会在一些情况下解析成为内网IP嘛？我也没搜集其他资料，还请指教。

**Comment by rootmelo92118** [comment]
https://cloud.tencent.com/developer/article/2055016
