### ISSUE TITLE
IPv6地址作为SNI时会匹配private规则的可能性

### ISSUE THREAD

**Issue by kabegoe** [v2fly/domain-list-community#1395]
当IPv6地址作为SNI时，会匹配
https://github.com/v2fly/domain-list-community/blob/7d24ecd45c7aecc3e23bfc4dce5964dfdc505858/data/private#L121-L122
`private`的这条规则。

巧合的是，IPv4地址作为SNI时并不会出现问题。其原因是IPv4地址本身包含`.`，恰好会被排除掉。

是否可以考虑把此规则替换成`regexp:^[^.:]+$`?

**Comment by IceCodeNew** [comment]
> 当IPv6地址作为SNI时，会匹配
> 
> https://github.com/v2fly/domain-list-community/blob/7d24ecd45c7aecc3e23bfc4dce5964dfdc505858/data/private#L121-L122
> 
> 
> `private`的这条规则。
> 巧合的是，IPv4地址作为SNI时并不会出现问题。其原因是IPv4地址本身包含`.`，恰好会被排除掉。
> 
> 是否可以考虑把此规则替换成`regexp:^[^.:]+$`?

Good catch

**Comment by database64128** [comment]
It's important to note that this issue was originally posted as SagerNet/sing-box#305.

I don't think this project should account for the possibility that some programs may match **string representations of IP addresses** against **domain** rules. Especially in this case, it should be a trivial fix for sing-box. sing-box should have checked whether the SNI is a string representation of an IP before matching it against domain rules.

**Comment by IceCodeNew** [comment]
> It's important to note that this issue was originally posted as SagerNet/sing-box#305.
> 
> I don't think this project should account for the possibility that some programs may match **string representations of IP addresses** against **domain** rules. Especially, in this case, it should be a trivial fix for sing-box. sing-box should have checked whether the SNI is a string representation of an IP before matching it against domain rules.

You got a point here. Yet I still would like to make the regex expression more accurate.

**Comment by nekohasekai** [comment]
As far as I know, this SNI extension is not sent when connecting to an IP address.

**Comment by mazzz1y** [comment]
> I don't think this project should account for the possibility that some programs may match string representations of IP addresses against domain rules. Especially in this case, it should be a trivial fix for sing-box. sing-box should have checked whether the SNI is a string representation of an IP before matching it against domain rules.

> As far as I know, the SNI extension is not sent when connecting to an IP address.

I think that rule should not work with garbage in sni header, regardless of why it was there. Thats why I submit PR with strict checking above. If maintainers not agree with that let's just close it
