### ISSUE TITLE
git clone 时 数据 未走vpn代理

### ISSUE THREAD

**Issue by whisky-12** [v2fly/domain-list-community#1402]
在规则为全局时， 对github youtube 等网站访问，可以发现在控制台中的抓包信息，节点流量传输正常。
但在使用git clone 下拉 远程仓库文件时， vpn节点 没有生效 
![image](https://user-images.githubusercontent.com/79358023/210524408-0294e7d1-29c6-4d1d-91de-5ee20872db18.png)

**Comment by IceCodeNew** [comment]
请不要直接在这个项目提问代理软件使用的问题，除非你已经在上游提问过后，定位到了问题是发生在域名归类数据上。
另外提问请打码敏感信息，不要把机场节点的域名全都露出来了。

**Comment by IceCodeNew** [comment]
先去 v2fly/v2ray-core 提 issue

**Comment by kslr** [comment]
如果是走 ssh 的，需要小乌龟单独配代理
