### ISSUE TITLE
麻烦增加openai的域名规则，谢谢

### ISSUE THREAD

**Issue by lovelygfj** [v2fly/domain-list-community#1430]
目的是通过WARP使用ChatGPT

**Comment by IceCodeNew** [comment]
already done in #1427

**Comment by toyo2333** [comment]
> 目的是通过WARP使用ChatGPT

出现了异常没有 我之前也是可以用，但这几天，打开页面就不对了，比如对话历史显示不出来，一些按钮显示不出来。
