### ISSUE TITLE
建议给/data/steam中“steamcontent.com”加“@cn”标签

### ISSUE THREAD

**Issue by simplerick-simplefun** [v2fly/domain-list-community#1441]
目前steam商店、好友、工坊的稳定访问是需要套代理的，而下载游戏的流量则不需要。
在steam@cn设置成直连的情况下：
如果steamcontent.com被设置为通过代理连接，那么下载游戏的流量就会通过代理连接*.steamcontent.com来下载。
而将steamcontent.com设置为直连后，steam客户端就能正常的从steam@cn中的域名中直连下载了。
https://github.com/v2fly/domain-list-community/blob/fd1dd4289067976f850fdadf14dfb34a792a5ef7/data/steam#L6

使用背景和需求性参考：https://github.com/2dust/v2rayN/issues/2462

**Comment by rootmelo92118** [comment]
歡迎提交pull request

**Comment by IceCodeNew** [comment]
> 歡迎提交pull request

未来如果提了 PR，我个人意见是不接受。绝大多数情况下，域名的维护规则都要求贴合实际情况，用户可以根据自己的需要调整路由规则的写法，或是自己 fork 项目来修改。
