### ISSUE TITLE
supercell.com被错误包含进了geosite:cn

### ISSUE THREAD

**Issue by vrichv** [v2fly/domain-list-community#1469]
> @KukiSa 代码有问题，supercell.com及所有下级域名一般都是使用非中国的亚马逊云，此代码包括了supercell.com，使到geosite:cn内包含了不应该直连的supercell.com，导致链接不稳定引发游戏偶发性断联。请删除此行。
> 
> supercell.com supercellcommunity.cn @cn supercellsupport.cn @cn
> 
> nslookup supercell.com 114.114.114.114 服务器: public1.114dns.com Address: 114.114.114.114 非权威应答: 名称: supercell.com Addresses: 13.225.103.54 13.225.103.56 13.225.103.71
> 
> nslookup supercell.com 223.5.5.5 服务器: public1.alidns.com Address: 223.5.5.5 非权威应答: 名称: supercell.com Addresses: 54.192.18.98 54.192.18.95 54.192.18.120 54.192.18.115
> 
> 域名/IP 获取的IP地址 数字地址 IP的物理位置 18.66.122.41 18.66.122.41 306346537 德国黑森法兰克福 亚马逊云 18.66.122.45 18.66.122.45 306346541 德国黑森法兰克福 亚马逊云 18.66.122.57 18.66.122.57 306346553 德国黑森法兰克福 亚马逊云 18.66.122.32 18.66.122.32 306346528 德国黑森法兰克福 亚马逊云 13.33.174.113 13.33.174.113 220311153 法国巴黎 亚马逊云 13.33.174.9 13.33.174.9 220311049 法国巴黎 亚马逊云 143.204.86.50 143.204.86.50 2412533298 日本东京 亚马逊云 143.204.86.78 143.204.86.78 2412533326 日本东京 亚马逊云 13.35.49.49 13.35.49.49 220410161 日本东京 亚马逊云 13.35.49.27 13.35.49.27 220410139 日本东京 亚马逊云 13.33.174.66 13.33.174.66 220311106 法国巴黎 亚马逊云 143.204.215.120 143.204.215.120 2412566392 德国黑森法兰克福 亚马逊云 13.226.225.44 13.226.225.44 232972588 美国加利福尼亚洛杉矶 亚马逊云 13.33.174.117 13.33.174.117 220311157 法国巴黎 亚马逊云 143.204.86.118 143.204.86.118 2412533366 日本东京 亚马逊云 13.35.49.101 13.35.49.101 220410213 日本东京 亚马逊云 143.204.215.46 143.204.215.46 2412566318 德国黑森法兰克福 亚马逊云 143.204.215.13 143.204.215.13 2412566285 德国黑森法兰克福 亚马逊云 13.225.114.27 13.225.114.27 232878619 韩国首尔 亚马逊云 13.225.114.101 13.225.114.101 232878693 韩国首尔 亚马逊云 13.225.114.58 13.225.114.58 232878650 韩国首尔 亚马逊云 13.225.114.89 13.225.114.89 232878681 韩国首尔 亚马逊云 65.9.86.12 65.9.86.12 1091130892 荷兰北荷兰省阿姆斯特丹 亚马逊云 65.9.86.106 65.9.86.106 1091130986 荷兰北荷兰省阿姆斯特丹 亚马逊云 65.9.86.4 65.9.86.4 1091130884 荷兰北荷兰省阿姆斯特丹 亚马逊云 65.9.86.82 65.9.86.82 1091130962 荷兰北荷兰省阿姆斯特丹 亚马逊云 13.226.225.121 13.226.225.121 232972665 美国加利福尼亚洛杉矶 亚马逊云 13.226.225.60 13.226.225.60 232972604 美国加利福尼亚洛杉矶 亚马逊云 13.227.254.80 13.227.254.80 233045584 新加坡 亚马逊云 13.227.254.113 13.227.254.113 233045617 新加坡 亚马逊云 13.227.254.5 13.227.254.5 233045509 新加坡 亚马逊云 54.192.18.120 54.192.18.120 918557304 中国香港 亚马逊云 54.192.18.115 54.192.18.115 918557299 中国香港 亚马逊云 143.204.86.79 143.204.86.79 2412533327 日本东京 亚马逊云 13.224.189.88 13.224.189.88 232832344 德国黑森法兰克福 亚马逊云 13.224.189.29 13.224.189.29 232832285 德国黑森法兰克福 亚马逊云 13.224.189.85 13.224.189.85 232832341 德国黑森法兰克福 亚马逊云 13.35.49.115 13.35.49.115 220410227 日本东京 亚马逊云 13.226.225.52 13.226.225.52 232972596 美国加利福尼亚洛杉矶 亚马逊云 143.204.215.49 143.204.215.49 2412566321 德国黑森法兰克福 亚马逊云 18.160.41.47 18.160.41.47 312486191 美国 亚马逊云 18.160.41.124 18.160.41.124 312486268 美国 亚马逊云 18.160.41.29 18.160.41.29 312486173 美国 亚马逊云 18.160.41.99 18.160.41.99 312486243 美国 亚马逊云 99.86.207.57 99.86.207.57 1666633529 韩国首尔 亚马逊云 99.86.207.69 99.86.207.69 1666633541 韩国首尔 亚马逊云 99.86.207.16 99.86.207.16 1666633488 韩国首尔 亚马逊云 99.86.207.53 99.86.207.53 1666633525 韩国首尔 亚马逊云 13.225.103.71 13.225.103.71 232875847 中国香港 亚马逊云 13.225.103.56 13.225.103.56 232875832 中国香港 亚马逊云 13.225.103.52 13.225.103.52 232875828 中国香港 亚马逊云 65.8.11.128 65.8.11.128 1091046272 马来西亚吉隆坡吉隆坡 亚马逊云 65.8.11.31 65.8.11.31 1091046175 马来西亚吉隆坡吉隆坡 亚马逊云 65.8.11.64 65.8.11.64 1091046208 马来西亚吉隆坡吉隆坡 亚马逊云 54.192.18.95 54.192.18.95 918557279 中国香港 亚马逊云 13.225.142.86 13.225.142.86 232885846 美国加利福尼亚洛杉矶 亚马逊云 13.225.142.75 13.225.142.75 232885835 美国加利福尼亚洛杉矶 亚马逊云 13.225.142.123 13.225.142.123 232885883 美国加利福尼亚洛杉矶 亚马逊云 54.192.18.98 54.192.18.98 918557282 中国香港 亚马逊云 13.35.24.54 13.35.24.54 220403766 中国台湾台北 亚马逊云 13.35.24.99 13.35.24.99 220403811 中国台湾台北 亚马逊云 13.35.24.125 13.35.24.125 220403837 中国台湾台北 亚马逊云 13.227.254.21 13.227.254.21 233045525 新加坡 亚马逊云 18.66.15.5 18.66.15.5 306319109 奥地利维也纳 亚马逊云 18.66.15.2 18.66.15.2 306319106 奥地利维也纳 亚马逊云 18.66.15.122 18.66.15.122 306319226 奥地利维也纳 亚马逊云 18.65.185.20 18.65.185.20 306297108 日本东京 亚马逊云 18.65.185.94 18.65.185.94 306297182 日本东京 亚马逊云 18.65.185.70 18.65.185.70 306297158 日本东京 亚马逊云 18.154.132.83 18.154.132.83 312116307 美国加利福尼亚洛杉矶 亚马逊云 18.154.132.97 18.154.132.97 312116321 美国加利福尼亚洛杉矶 亚马逊云 18.154.132.112 18.154.132.112 312116336 美国加利福尼亚洛杉矶 亚马逊云 18.154.132.46 18.154.132.46 312116270 美国加利福尼亚洛杉矶 亚马逊云 13.224.189.89 13.224.189.89 232832345 德国黑森法兰克福 亚马逊云 13.35.7.90 13.35.7.90 220399450 中国台湾台北 亚马逊云 13.35.7.43 13.35.7.43 220399403 中国台湾台北 亚马逊云 13.35.7.83 13.35.7.83 220399443 中国台湾台北 亚马逊云 13.35.8.6 13.35.8.6 220399622 新加坡 亚马逊云 13.35.8.81 13.35.8.81 220399697 新加坡 亚马逊云 13.35.8.63 13.35.8.63 220399679 新加坡 亚马逊云 13.35.8.126 13.35.8.126 220399742 新加坡 亚马逊云

~~`supercell.com` 不包含在 `tencent` 和 `tencent-games` 中，无需删除。~~

不好意思，`supercell.com` 在  `tencent-games` 第 93 行。

_Originally posted by @KukiSa in https://github.com/v2fly/domain-list-community/issues/1132#issuecomment-1371886827_

**Comment by rootmelo92118** [comment]
歡迎提交拉取請求。
