### ISSUE TITLE
google-scholar未包含scholar.googleusercontent

### ISSUE THREAD

**Issue by SASBSC** [v2fly/domain-list-community#1497]
谷歌学术下载引用时跳转至scholar.googleusercontent，现有文件里未包含scholar.googleusercontent，不能分流

**Comment by IceCodeNew** [comment]
需要提供证据，另外可以考虑自己提一个 PR 帮忙修复。不会流程可以学，我愿意帮助

**Comment by SASBSC** [comment]
> 需要提供证据。 另外可以考虑自己提一个 PR 帮忙修复。不会流程可以学，我愿意帮助。

好的，我学习下
