### ISSUE TITLE
Solve multiple root node problem and decrease it

### ISSUE THREAD

**Issue by rootmelo92118** [v2fly/domain-list-community#1561]
I write a script to find the categories which are not included by other categories. And I get this result.
```
category-finance
adobe-activation
category-network-security
speedtest
pandanet
test
category-pt
category-ads-all
cn
category-public-tracker
cowlevel
biliplus
tld-opennic
chemequations
dslreports
private
tor
apple-update
category-enhance-gaming
showtimeanytime
geolocation-!cn
category-ir
downloadly
category-ru-gov
hubblephone
```
Some categories should not be included by others. That is according to the discussion with other collaborators so I won't touch them.
Besides, I will create some pull requests to include them in others.

**Comment by IceCodeNew** [comment]
Would you mind me postponing the review till April? It is indeed a good idea, but I think I can only make a call when I have time to review all of this; Digesting them one by one may lead to misunderstanding and a lapse in judgment.

BTW, you did it very well in splitting the changes into several small PRs.
However, you could make it better by just opening this issue, and waiting till you have had a discussion with people who is likely to review the PRs.
You can start your work after you have put some effort to make sure that any overlooking has been caught in advance, and reviewers show interest in your proposal.
@rootmelo92118

**Comment by rootmelo92118** [comment]
Oh, I am sorry to make you misunderstand. For these categories, my strategy is to include them in existing categories. If you think it should not belong to some categories, welcome to make a discussion.
@IceCodeNew

**Comment by IceCodeNew** [comment]
The newest ETA is the coming Saturday night, thanks for everyone being patient.

**Comment by IceCodeNew** [comment]
Finally, I can have some rest...
