### ISSUE TITLE
warp openai用不了,帮忙修复

### ISSUE THREAD

**Issue by sirbai** [v2fly/domain-list-community#1583]

**Comment by IceCodeNew** [comment]
We can not help since there is just no info or background mentioned in this issue.

**Comment by sirbai** [comment]
https://chat.openai.com/chat 又可以用了
昨晚添加 openai warp 没有生效
非常感谢

**Comment by SakuraSakuraSakuraChan** [comment]
有些openai的域名因为不是专有的所以无法添加进geosite，自己写一下规则，比如 auth0.com challenges.cloudflare.com 等

**Comment by toyo2333** [comment]
> https://chat.openai.com/chat 又可以用了 昨晚添加 openai warp 没有生效 非常感谢

我是通关warp代理访问GTP的，但是有一个问题，前几天都正常，但是今天页面打开后，对话历史记录和一些按钮就没有了。是不是因为缺少域名导致的？一个一个找域名太费劲了。。。你是怎么做的呢？
