### ISSUE TITLE
tiktok.com为什么归到cn?

### ISSUE THREAD

**Issue by iwoomi** [v2fly/domain-list-community#1585]
服务器路由规则添加以下配置，本来是想禁止国内ip走服务器再绕回来，但没想到tiktok.com也因此被禁，不太明白为什么把tiktok.com放到cn域名中？
```
{
    "type": "field",
    "outboundTag": "block",
    "domain": [
        "geosite:cn"
    ]
}
```

**Comment by IceCodeNew** [comment]
https://github.com/v2fly/domain-list-community/blob/e57248760c7ce3cbcaccc20279053da266678ed2/data/tiktok#L5

你用的 .dat 数据库没有正确剔除掉 `@!cn` 的域名。可以试试下游项目 https://github.com/Loyalsoldier/domain-list-custom

**Comment by iwoomi** [comment]
> https://github.com/v2fly/domain-list-community/blob/e57248760c7ce3cbcaccc20279053da266678ed2/data/tiktok#L5
> 
> 你用的 .dat 数据库没有正确剔除掉 `@!cn` 的域名。可以试试下游项目 https://github.com/Loyalsoldier/domain-list-custom

啊？这并不是我自己去挑选哪个来用的，而是我直接安装的xray，它自己就自带这两个dat文件，而xray的这两个dat文件应该是来自这个项目的吧？

**Comment by IceCodeNew** [comment]
那你可以自己换这两个文件。总之域名在项目里标记是正确的，dat 文件生成虽然有逻辑但不打算修复（因为之前提修复 pr 的人等不到 pr 合并就自己开下游项目了，也就是我推荐给你的那个）
因此你的问题在这个项目得不到解决。

**Comment by rootmelo92118** [comment]
> > https://github.com/v2fly/domain-list-community/blob/e57248760c7ce3cbcaccc20279053da266678ed2/data/tiktok#L5
> > 
> > 你用的 .dat 数据库没有正确剔除掉 `@!cn` 的域名。可以试试下游项目 https://github.com/Loyalsoldier/domain-list-custom
> 
> 啊？这并不是我自己去挑选哪个来用的，而是我直接安装的xray，它自己就自带这两个dat文件，而xray的这两个dat文件应该是来自这个项目的吧？
> 
> 我是使用[XTLS/Xray-install](https://github.com/XTLS/Xray-install)一键脚本安装的
> 
> ```shell
> bash -c "$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ install
> ```

是，但不建議直接使用。有部分歷史遺留問題是本倉庫尚未解決但是其他第三方倉庫已解決。
