### ISSUE TITLE
.me 域名不应该归入 tld-!cn

### ISSUE THREAD

**Issue by vincentlauvlwj** [v2fly/domain-list-community#1606]
注意到前几天的这个提交把 .me 域名加入了 tld-!cn 分类 https://github.com/v2fly/domain-list-community/commit/46129c5211ce14a8ff0869fe1501feb6fda7c44b

.me 域名虽然曾经是黑山共和国的国家域名，但早已开放注册，如今可以视为国际域名，大多被用来作为个人博客之类的站点，加入 tld-!cn 会导致这类站点默认都走代理

**Comment by rootmelo92118** [comment]
但是，`.me`在大陸並不開放備案，走代理似乎沒有什麼問題。

**Comment by rootmelo92118** [comment]
歡迎提交Pull Request進行相關更正。

**Comment by vincentlauvlwj** [comment]
12 月 8 日的一个提交，又把 .me 域名加入了 tld-!cn，问题再次出现 https://github.com/v2fly/domain-list-community/commit/7af994cb70156617ece4686d2dec2fda58fcefbf

**Comment by rootmelo92118** [comment]
> 12 月 8 日的一个提交，又把 .me 域名加入了 tld-!cn，问题再次出现 [7af994c](https://github.com/v2fly/domain-list-community/commit/7af994cb70156617ece4686d2dec2fda58fcefbf)

PR is welcome.
