### ISSUE TITLE
排除 category-ads-all 属性中 click.discord.com

### ISSUE THREAD

**Issue by InnocenseYu** [v2fly/domain-list-community#1614]
使用 geosite: category-ads-all，无法验证来自新地点的Discord登录

**Comment by rootmelo92118** [comment]
在該分類中沒有尋獲該域名

**Comment by rootmelo92118** [comment]
@InnocenseYu 我想問一下你所使用的geosite資料庫是不是這個？https://github.com/Loyalsoldier/v2ray-rules-dat

**Comment by InnocenseYu** [comment]
> @InnocenseYu ~我想問一下你所使用的geosite資料庫是不是這個？~ 經查證你的確是使用這個專案而產生的原因，不在本專案負責範圍內。 專案：https://github.com/Loyalsoldier/v2ray-rules-dat P.S. 2023年04月14日，有使用者從該專案中移除了該域名，你更新一下資料庫就能使用了[Loyalsoldier/v2ray-rules-dat#279](https://github.com/Loyalsoldier/v2ray-rules-dat/pull/279)



> @InnocenseYu ~我想問一下你所使用的geosite資料庫是不是這個？~ 經查證你的確是使用這個專案而產生的原因，不在本專案負責範圍內。 專案：https://github.com/Loyalsoldier/v2ray-rules-dat P.S. 2023年04月14日，有使用者從該專案中移除了該域名，你更新一下資料庫就能使用了[Loyalsoldier/v2ray-rules-dat#279](https://github.com/Loyalsoldier/v2ray-rules-dat/pull/279)

更新后已经解决，谢谢你~
