### ISSUE TITLE
qingting.fm走代理

### ISSUE THREAD

**Issue by Btu2023V** [v2fly/domain-list-community#1617]
最新的geosite.dat，黑名单分流qingting.fm走了代理。但删除黑名单下proxy中的geosite:tld-!cn后，qingting.fm正常直连。

**Comment by rootmelo92118** [comment]
`tld-!cn`的作用是將不屬於大陸及無法被備案的頂級域逕行歸類，與可否直連沒有直接關聯。

**Comment by Btu2023V** [comment]
我明白.fm被列入tld-!cn属正常，我的意思是qingting.fm属于CN类别域名不应该走代理。

**Comment by rootmelo92118** [comment]
> 我明白.fm被列入tld-!cn属正常，我的意思是qingting.fm属于CN类别域名不应该走代理。

有什麼樣的證據證明其屬於中國大陸域名？

**Comment by Btu2023V** [comment]
> > 我明白.fm被列入tld-!cn属正常，我的意思是qingting.fm属于CN类别域名不应该走代理。
> 
> 有什麼樣的證據證明其屬於中國大陸域名？

不是大陆域名，为何加入到geosite:cn当中？再说qingting.fm是家大陆公司尽人皆知。

**Comment by rootmelo92118** [comment]
> > > 我明白.fm被列入tld-!cn属正常，我的意思是qingting.fm属于CN类别域名不应该走代理。
> > 
> > 
> > 有什麼樣的證據證明其屬於中國大陸域名？
> 
> 不是大陆域名，为何加入到geosite:cn当中？再说qingting.fm是家大陆公司尽人皆知。

我建議調整路由順序來解決這個問題

**Comment by Btu2023V** [comment]
> > > > 我明白.fm被列入tld-!cn属正常，我的意思是qingting.fm属于CN类别域名不应该走代理。
> > > 
> > > 
> > > 有什麼樣的證據證明其屬於中國大陸域名？
> > 
> > 
> > 不是大陆域名，为何加入到geosite:cn当中？再说qingting.fm是家大陆公司尽人皆知。
> 
> 我建議調整路由順序或政策來解決這個問題

这个当然。只是疑惑更新后的geosite.dat会出现这个问题而之前的没有。
