### ISSUE TITLE
正则表达式前缀regex应改为regexp

### ISSUE THREAD

**Issue by xyzhou-1** [v2fly/domain-list-community#163]
问题:regex未被识别,编写的规则失效
[代码](https://github.com/v2ray/v2ray-core/blob/720c0d0c4bd6e1b4937cd003dd767834bc25d622/infra/conf/router.go#L290)说明的最清楚:
![image](https://user-images.githubusercontent.com/47747466/90620595-423aec00-e245-11ea-8cc5-3f6f5ba513d8.png)
[文档](https://www.v2fly.org/config/routing.html#ruleobject)也说的是regexp
![image](https://user-images.githubusercontent.com/47747466/90620952-b1184500-e245-11ea-8cce-349c7c273753.png)

最后自己复现也是预期的结果,regex无效,regexp有效.结果就不贴了.
regrex共有11处, https://github.com/v2fly/domain-list-community/search?q=regex&type=

**Comment by studentmain** [comment]
[代码](https://github.com/v2fly/domain-list-community/blob/f587eaeb04d7949b1e4f310c701924bfb655721c/main.go#L73)
https://github.com/v2fly/domain-list-community/blob/f587eaeb04d7949b1e4f310c701924bfb655721c/main.go#L73

[文档](https://github.com/v2fly/domain-list-community/blob/cc4ac26869aeefdfd31c50696cf11a93a1af10ee/README.md#how-it-works)
> 6. Generate each `regex:` line into a [regex domain routing rule](https://github.com/v2fly/v2ray-core/blob/master/app/router/config.proto#L19).

**Comment by xyzhou-1** [comment]
我说的代码是v2ray-core的解析代码,你给的是geosite的生成代码.还有你可以复现一遍.我看的是假的文档?

**Comment by EpLiar** [comment]
@Loyalsoldier 帮忙测试一下

**Comment by studentmain** [comment]
geosite直接转成protobuf格式，v2ray-core根本不会关心geosite使用什么记法

> 
> 
> 我说的代码是v2ray-core的解析代码,你给的是geosite的生成代码.还有你可以复现一遍.我看的是假的文档?而且我给文档只是辅助说明,这代码给的够明白了

**Comment by Loyalsoldier** [comment]
@xyzhou-1 你说的这个代码，是用来解析 V2Ray 配置文件中，用户手写的规则的，配置文件中的正则表达式，用 `regexp:` 开头。
`domain-list-community` 这个项目中的正则规则，用 `regex:` 开头。两者并无关联。

**Comment by xyzhou-1** [comment]
我知道了,抱歉,我的问题,我把geosite仓库里的规则直接复制粘贴了,脑子被门夹了,没想清楚就提了issue,对再次造成的困扰表示抱歉.

**Comment by studentmain** [comment]
我想我们需要加个说明，指出直接复制粘贴不能用
