### ISSUE TITLE
Do you have a category for social media platforms and youtube?

### ISSUE THREAD

**Issue by lostsoul6** [v2fly/domain-list-community#1636]
Hello my friends ,

I need to block access to social media and youtube on one of my servers . I currently have blocked the porn sites using the following rule  :  
{
        "type": "field",
        "outboundTag": "blocked",
        "domain": [
          "geosite:category-porn"
        ]
      }
    ]
  },

Is it possible to block big social media platforms like Instagram , Telegram , Twitter and tiktok the same way ?

**Comment by bijoni** [comment]
Try this.

"domain": [
"geosite:category-porn",
"geosite:category-social-media-!cn",
"geosite:category-social-media-cn"
]

**Comment by rootmelo92118** [comment]
```json
{
    "type":"field",
    "outboundTag":"blocked",
    "domain":[
        "geosite:category-porn",
        "geosite:category-social-media-!cn",
        "geosite:category-social-media-cn"
    ]
},
{
    "type":"field",
    "outboundTag":"blocked",
    "ip":[
        "geoip:telegram",
        "geoip:facebook",
        "geoip:twitter"
    ]
}
```
