### ISSUE TITLE
關於分類命名規則相關規範 (徵求意見稿)

### ISSUE THREAD

**Issue by rootmelo92118** [v2fly/domain-list-community#1643]
今日針對 #1636 號問題給予答覆時，發現部分命名規則存在不統一之情形。如下所示：

1. 用於區分大陸地區及非大陸地區之類別名稱：
```
category-social-media-cn
category-social-media-!cn
mihoyo-cn
mihoyo-!cn
. . . . . . . . (etc.)
```
上述範例將類別名稱放置於前，在尾端加上地域性標示。

2. 用於標示於限定為某國家或地區之類別名稱：
```
category-ru-gov
category-ir-gov
category-ir-social-media
category-ir-travel
. . . . . . . . (etc.)
```
上述範例將`category`放置於前，中間加入國家代碼，最後補上類別名稱。

本欄討論目的為是否應當制定相關規範統一具有地域標示之類別名稱。
提出本議題進行討論之原因為，讓類別名稱進行統一格式規範有助於維護者進行維護工作及讓使用者可直覺化調用相關類別。

**Comment by rootmelo92118** [comment]
@IceCodeNew @EpLiar

**Comment by IceCodeNew** [comment]
> @IceCodeNew @EpLiar

我觉得是很不错的想法，你想怎么做。

**Comment by rootmelo92118** [comment]
> > @IceCodeNew @EpLiar
> 
> 我觉得是很不错的想法，你想怎么做。

我目前的想法是將`category-ir(ru)-xxx`的類別轉換至`category-xxx-ir(ru)`。

**Comment by IceCodeNew** [comment]
> > > @IceCodeNew @EpLiar
> > 
> > 我觉得是很不错的想法，你想怎么做。
> 
> 我目前的想法是將`category-ir(ru)-xxx`修改為`category-xxx-ir(ru)`。

我不反对，趁现在早点开始做还不至于影响太大。你可以提 PR 直接 rename 这些文件。
但是建议你提前和最近活跃的伊朗贡献者都通通气。
