### ISSUE TITLE
Announce and discuss the operation of renaming

### ISSUE THREAD

**Issue by rootmelo92118** [v2fly/domain-list-community#1646]
@fakhamatia @nickaein @IRConf @keikhosrow @BobZombiE69 @mmrabbani @bootmortis @thisismzm @pulsarice @alirezax5 @aminvakil @debMan @ShahinSorkh @molaeiali @WGOS

According to #1643 (I know this is Chinese, so I will use English to explain what we will do.), we decide to rename the `category-ir(ru)-xxx` to `category-xxx-ir(ru)`. The reason is that before the Iranian category creation, we already used `category-xxx-cn(!cn)` to tag it inside or outside mainland China. We want to keep the naming convention consistent. Is anyone has opinion?

**Comment by nickaein** [comment]
Hi Kitayama!

Thanks for the heads up!

As a contributor, I found `category-ir-xxx` convention helpful as it enables easy sorting and clustering of all Iranian categories into one group, allowing me to quickly identify the most suitable category for a new domain without the need for additional search. 

In similar way, it can be helpful for new contributors too and help them to understand what categories are present and reduce going back and forth in PRs caused by misclassifications.

Nevertheless, having a consistent naming convention is certainly helpful and I would be happy to help either approach.

**Comment by aminvakil** [comment]
Fine by me, normally an alias for a while and having a warning for a period of time, which gives users they should switch to new name would be more appropriate.

But I don't think it can be done in this repository, and I don't know if it's possible at all by the nature of v2ray configurations to show a warning for domains.

Anyway thanks for heads up and thanks for maintening this

**Comment by rootmelo92118** [comment]
> Fine by me, normally an alias for a while and having a warning for a period of time, which gives users they should switch to new name would be more appropriate.
> 
> But I don't think it can be done in this repository, and I don't know if it's possible at all by the nature of v2ray configurations to show a warning for domains.
> 
> Anyway thanks for heads up and thanks for maintening this

Thanks for your reply. But actually, it can be done in this repository. You can see PR #1644 .

**Comment by molaeiali** [comment]
It's ok to me, thanks for the heads-up

**Comment by rootmelo92118** [comment]
> Hi Kitayama!
> 
> Thanks for the heads up!
> 
> I found `category-ir-xxx` convention helpful as it enables easy sorting and clustering of all Iranian categories into one group, allowing me to quickly identify the most suitable category for a new domain without the need for additional search.
> 
> In similar way, it can be helpful for new contributors too and help them to understand what categories are present and reduce going back and forth in PRs caused by misclassifications.
> 
> Nevertheless, having a consistent naming convention is certainly helpful and I would be happy to help either approach.

I understand your concerns and thoughts, but when I use GitHub to search `category-cn`, GitHub will return me the result of `category-xxx-cn` at the same time. So, after this modification, you still can use `category-ir` to search for the category which belongs to Iran. 
<img width="1440" alt="截圖 2023-05-07 上午11 44 44" src="https://user-images.githubusercontent.com/32770959/236656619-9163a6cb-6646-41a1-b126-4e94a98d17de.png">

**Comment by bootmortis** [comment]
Thanks for the heads-up; we already read all IR-related domains from `category-ir` ([here](https://github.com/bootmortis/iran-hosted-domains/blob/0b34cf259f13c648ca68afb330794953bb066193/src/get_domians.py#L38C23-L48)), so fine by me.
