### ISSUE TITLE
TODO: revert #863 

### ISSUE THREAD

**Issue by IceCodeNew** [v2fly/domain-list-community#1657]
There was a discussion about it, and we are planning to revert the PR #863  
This issue is for notification and tracking the progress.  
  
For anyone who may concern about the discussion, please refer to the following:  
* https://github.com/v2fly/domain-list-community/pull/1655#issuecomment-1543214093

**Comment by rootmelo92118** [comment]
I have no objection to revert the PR, after all, there is no guarantee that there are any remaining problems. But at the same time, I don't think the original PR is completely worthless. I have saved domains that will be removed. I will check these domain names again, and the domain names after the check will be re-added to `category-porn`.

**Comment by rootmelo92118** [comment]
Wait a minute. I used OpenDNS to resolve which domains are belonging to pornographic websites. (also remove the domain which is expired). I got 908 domains, and the total domains have 994. It means most of the domain will be re-added. Are you sure you want to revert it?

**Comment by IceCodeNew** [comment]
> Wait a minute. I used OpenDNS to resolve which domains are belonging to pornographic websites. (also remove the domain which is expired). I got 908 domains, and the total domains have 994. It means most of the domain will be re-added. Are you sure you want to revert it? [outputdomain.txt](https://github.com/v2fly/domain-list-community/files/11460250/outputdomain.txt)

Yes, I am going to revert that PR no matter what. The nature of the problem is copying the contents of a third-party source, which brings to us the problem of copyleft, sync & quality.
You may spot the miscategorized domains based on OpenDNS's labeling or something, but even if it is enough for salvaging the qualified parts, there are still problems that we can not solve.
After all, salvaging pornographic sited based on a list of domains that are blocked in Korea is not a good idea.

**Comment by Loyalsoldier** [comment]
Any progress?
