### ISSUE TITLE
geosite:tvb不生效

### ISSUE THREAD

**Issue by soundghost** [v2fly/domain-list-community#1683]
最近想看tvb的老剧，于是在路由里设置了geosite:tvb走北美的一个vps，但是打开tvbanywhere却还是提示该服务仅针对北美地区开放。

我在data里搜tvb，能看到tvb的规则包含在内，但是实际上tvb却无法观看。

请问是我的设置有误还是什么原因导致的呢？

谢谢。

**Comment by IceCodeNew** [comment]
这个问题应该是你代理配置的路由规则的问题，和这个项目无关。你不应该在这里提问，这里也没有人可以帮助你。
