### ISSUE TITLE
OpenAI domains  are not update

### ISSUE THREAD

**Issue by toyo2333** [v2fly/domain-list-community#1704]
# Main domain
ai.com
openai.com

# CDN & API
full:chat.openai.com.cdn.cloudflare.net
full:openaiapi-site.azureedge.net
full:openaicom-api-bdcpf8c6d2e9atf6.z01.azurefd.net
full:openaicomproductionae4b.blob.core.windows.net
full:production-openaicom-storage.azureedge.net

# tracking
full:o33249.ingest.sentry.io @ads
full:openaicom.imgix.net @ads

use warp to unlock chatgpt, set this in Xray routing rules, it works for a week~

but, frrom yesterday it did not work ~ The page can be opened throw WARP IP, but none of the functions work, and the list of historical conversations does not load。

please update the domains~

**Comment by IceCodeNew** [comment]
PR is welcome~

**Comment by rootmelo92118** [comment]
Could you provide the new domain?
