### ISSUE TITLE
关于如何更好地参与本项目

### ISSUE THREAD

**Issue by FDUZS** [v2fly/domain-list-community#1723]
我不知道你们 Collaborator 的工作流是怎样的，仅作为 Contributor 说说我的需求和看法

在提 PR #1714 #1715 之前，我一开始仅想到 epochmediagroup 这个文件，后来才找到 falungong
在看到 merge 被 revert 后找到了 soundofhope，有了 #1722
但我至今仍不知道下面这些域名是否已被收录，或者应放在哪个文件

在我看来，README 文件中的 Contribution guideline 几近于无
如果有这样一个（在线）工具，能够查询域名是否存在（存在的话输出文件名），并以知识图谱的形式展现文件间的相互联系会更好

```text
Input: example.com
Output: No / Yes, in file `example`
```

```text
aboluowang.com
broadpressinc.com
chinaaffairs.org
falundafamuseum.org
falungong.club
faluninfo.net
fawanghuihui.org
fgmtv.org
hopto.org
kanzhongguo.com
secretchina.com
starp2p.com
tiandixing.org
tiantibooks.org
tuidang.org
upholdjustice.org
xinsheng.net
yuanming.net
yuming.qxbbs.org
zhengwunet.org
zhenxiang.biz
zhuichaguoji.org
```

**Comment by rootmelo92118** [comment]
我是以geolocation-!cn返回DNS 127.0.0.1 來辨別 並篩選出未收錄域名
https://github.com/rootmelo92118/remove-invalid-domain-name/blob/master/che.py 這個腳本或許可以幫助你

**Comment by Loyalsoldier** [comment]
在 GitHub 的搜索框中基于本项目搜索需要添加的域名，即可发现该域名是否存在于本项目。

**Comment by FDUZS** [comment]
这样是可以，但未免刀耕火种了点

**Comment by IceCodeNew** [comment]
> 这样是可以，但未免刀耕火种了点

我个人是用 ripgrep 在本地代码仓库搜索要添加的域名，但是网页搜索也不坏。
