### ISSUE TITLE
Protection against IP address leak on zxinc.org

### ISSUE THREAD

**Issue by herberteuler** [v2fly/domain-list-community#1730]
I apologize for filing a separate issue for the same risk, albeit a PR for this has been filed previously (#1727). The PR has been closed with rejection, but the danger persists, hence this issue.

The risk lies in how [the IP geolocation query page](https://ip.zxinc.org/ipquery/) works: it displays two IP addresses, the IPv4 one and the IPv6 one. Without proper settings, it can be the case that one of them is the remote server IP address and the other the client's local IP address.

As I understand, @rootmelo92118 closed the PR because it did not satisfy the category rule: the site was added as a cn site while its IP address was from HK instead of mainland China.

However, it raises a question: By which criterion should a site be categorized? By geolocation or functionality? If the criterion is geolocation, this site should not be added as a cn site. On the other hand, if the criterion is functionality, it is then reasonable to add it as a cn site because it aims for usage in mainland China.

Either way, this potential risk should be resolved as it is too apparent an anomaly that one's IPv4 address and IPv6 address are from two distinct geolocations.

**Comment by rootmelo92118** [comment]
The rule of `geolocation-cn` is to store only the domain in which the IP belongs to the mainland of China.

**Comment by herberteuler** [comment]
Yes, I see. The file name suggests it is about geolocation.

Should there be another file for storing this kind of sites, whose geolocations are dissociated from their purposes?

**Comment by herberteuler** [comment]
> The file name suggests it is about geolocation.

In this sense, `geolocation` is unambiguous concerning criterion, while `geosite` is ambiguous. For example, there can be phishing sites outside mainland China but targeting users in mainland China, which, in my book, will still be cn sites.

**Comment by rootmelo92118** [comment]
Could you realize the situation of the ipv4 address belonging to the proxy server and ipv6 belonging to the native ip address?
According to my understanding, both of them will be proxied by the tool.
