### ISSUE TITLE
可否增加一个AI的分类表现

### ISSUE THREAD

**Issue by Bitcion** [v2fly/domain-list-community#1740]
当前流行的是bing ai跟chatgpt，未来这种产品会越来越多，最新推出的claude.ai还没有收录
这些产品大多会限制使用地区，建议构建一个 ai 大的标签分类统一收录

**Comment by rootmelo92118** [comment]
歡迎提交拉取請求

**Comment by FDUZS** [comment]
差不多两个月前我提过类似的 #1663
那时的情况是 Google Bard 仅面向英美地区，new Bing 的图片生成也只限于美国，ChatGPT 之类的更不用说，明确不支持大陆及港澳。不过，其他的如 Poe 等大量衍生应用其实并未过多限制
采取白名单代理模式的话，只需为几个特殊和常用的显式设置策略组即可，其他未命中的走默认代理
```text
OpenAI ---> `openai`
Google Bard ---> `google`
new Bing ---> `bing`
Claude ---> `anthropic` # claude.ai 昨天已经合并进去了
Poe ---> `quora`
```
