### ISSUE TITLE
拦截了bing主域名导致国内bing走代理

### ISSUE THREAD

**Issue by Voyager-8** [v2fly/domain-list-community#1796]
表内用主域名bing.com拦截导致cn.bing.com，www4.bing.com走代理

**Comment by Loyalsoldier** [comment]
请自行给相应域名添加规则

**Comment by Voyager-8** [comment]
我把gfw_list.conf里的bing.com改globle.bing.com能行，但自动更新会覆盖掉gfw_list.conf，白名单里添加cn.bing.com，www4.bing.com不生效
