### ISSUE TITLE
建议增加youtube这样的视频分类，这样看视频不怕大流量了。。

### ISSUE THREAD

**Issue by Rem1x-2019** [v2fly/domain-list-community#1803]
youtube什么的视频网站，建议增加这样的分类，这样分线路代理，不然视频流量大。。

**Comment by FDUZS** [comment]
https://github.com/v2fly/domain-list-community/blob/master/data/category-entertainment

https://github.com/v2fly/domain-list-community/blob/master/data/youtube
https://github.com/v2fly/domain-list-community/blob/master/data/netflix
https://github.com/v2fly/domain-list-community/blob/master/data/disney
https://github.com/v2fly/domain-list-community/blob/master/data/hbo
https://github.com/v2fly/domain-list-community/blob/master/data/hulu
等等……

**Comment by Rem1x-2019** [comment]
> https://github.com/v2fly/domain-list-community/blob/master/data/category-entertainment
> 
> https://github.com/v2fly/domain-list-community/blob/master/data/youtube https://github.com/v2fly/domain-list-community/blob/master/data/netflix https://github.com/v2fly/domain-list-community/blob/master/data/disney https://github.com/v2fly/domain-list-community/blob/master/data/hbo https://github.com/v2fly/domain-list-community/blob/master/data/hulu 等等……

谢谢，
不过这些好象没有集成到geosite里面，我用geosite:youtube  提示找不到数据，
我用的passwall2，

**Comment by FDUZS** [comment]
建议使用基于 clash 及其衍生内核的工具，分流上更方便
同时搭配 https://rules.kr328.app/ 使用 https://github.com/Kr328/V2rayDomains2Clash

**Comment by Rem1x-2019** [comment]
> 建议使用基于 clash 及其衍生内核的工具，分流上更方便 同时搭配 https://rules.kr328.app/ 使用 https://github.com/Kr328/V2rayDomains2Clash

不好意思，因为我是自己的服务器，设置很多次openclash，都不太行，
可能是我没设置好，设置有点麻烦。。。

**Comment by Rem1x-2019** [comment]
> > > https://github.com/v2fly/domain-list-community/blob/master/data/category-entertainment
> > > https://github.com/v2fly/domain-list-community/blob/master/data/youtube https://github.com/v2fly/domain-list-community/blob/master/data/netflix https://github.com/v2fly/domain-list-community/blob/master/data/disney https://github.com/v2fly/domain-list-community/blob/master/data/hbo https://github.com/v2fly/domain-list-community/blob/master/data/hulu 等等……
> > 
> > 
> > 谢谢， 不过这些好象没有集成到geosite里面，我用geosite:youtube 提示找不到数据， 我用的passwall2，
> 
> 按理说在data目录下的各目录都能被geosite的格式识别啊，你确保数据是完整的并且最新不？ 我之前用过这个youtube分类进行分流，没有问题；后来直接用的gfw包含了没单设，一切正常； （也是使用pw2）

https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat
我用的这个。。。没有youtube分类。。可能是我使用方式不对。。/笑哭

**Comment by rootmelo92118** [comment]
youtube 有單獨類別，不是很明白你的訴求

**Comment by rootmelo92118** [comment]
> > > > [`master`/data/category-entertainment](https://github.com/v2fly/domain-list-community/blob/master/data/category-entertainment?rgh-link-date=2023-08-24T14%3A26%3A33Z)
> > > > [`master`/data/youtube](https://github.com/v2fly/domain-list-community/blob/master/data/youtube?rgh-link-date=2023-08-24T14%3A26%3A33Z) [`master`/data/netflix](https://github.com/v2fly/domain-list-community/blob/master/data/netflix?rgh-link-date=2023-08-24T14%3A26%3A33Z) [`master`/data/disney](https://github.com/v2fly/domain-list-community/blob/master/data/disney?rgh-link-date=2023-08-24T14%3A26%3A33Z) [`master`/data/hbo](https://github.com/v2fly/domain-list-community/blob/master/data/hbo?rgh-link-date=2023-08-24T14%3A26%3A33Z) [`master`/data/hulu](https://github.com/v2fly/domain-list-community/blob/master/data/hulu?rgh-link-date=2023-08-24T14%3A26%3A33Z) 等等……
> > > 
> > > 
> > > 谢谢， 不过这些好象没有集成到geosite里面，我用geosite:youtube 提示找不到数据， 我用的passwall2，
> > 
> > 
> > 按理说在data目录下的各目录都能被geosite的格式识别啊，你确保数据是完整的并且最新不？ 我之前用过这个youtube分类进行分流，没有问题；后来直接用的gfw包含了没单设，一切正常； （也是使用pw2）
> 
> [Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat](https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat) 我用的这个。。。没有youtube分类。。可能是我使用方式不对。。/笑哭

順帶一題，那倉庫包含本倉庫的所有類別。
