### ISSUE TITLE
原神国际服更新域名错误地包括在了@cn

### ISSUE THREAD

**Issue by ahdiua** [v2fly/domain-list-community#1836]
原神国际服的启动器更新和游戏更新都用的
`autopatchhk.yuanshen.com`

理论上国际服应该使用`hoyoverse.com`的域名，这个锅属于米哈游。

```
nslookup autopatchhk.yuanshen.com
服务器:  public1.alidns.com
Address:  223.5.5.5

非权威应答:
名称:    a1881.v.akamai.net
Addresses:  23.2.13.50
          23.2.13.57
Aliases:  autopatchhk.yuanshen.com
          autopatchhk.yuanshen.com.akamaized.net
```
nslookup发现是解析到akamai的cdn上

**Comment by rootmelo92118** [comment]
這點其實當時我維護的時候已悉知，但是不太可能去把每個域名都抓出來，這個專案也無法單獨的排除特定域名，所以目前是維持現狀，如果真的出問題再進行解決。

**Comment by ahdiua** [comment]
> 這點其實當時我維護的時候已悉知，但是不太可能去把每個域名都抓出來，這個專案也無法單獨的排除特定域名，所以目前是維持現狀，如果真的出問題再進行解決。

原来如此，确实没有排除的办法，只有自行加入分流规则。

这个issue应该关掉吗？

**Comment by Chenyu550** [comment]
其实你去itdog或类似网站上ping一下就会发现，它是有国内的网宿科技cdn的。很奇怪的是，只有一半会解析到它，另一半会解析到Akamai（所以有一条冷知识是设置hosts指向国内cdn节点可以显著加快游戏更新速度）
