### ISSUE TITLE
New attributes

### ISSUE THREAD

**Issue by demarcush** [v2fly/domain-list-community#1855]
I propose adding additional attributes beside `@ads`, like `@nsfw`, `@torrent` and `@piracy` to better manage groups needed for making a parental-controlled environment for kids (and maybe elderly).

I'm currently working on my next patch to the project that includes a `category-piracy` group which includes `category-torrent` (consisting of `category-pt`, `category-public-tracker` and other manually inserted torrent sites in `geolocation-!cn`) and `category-anime` (formerly `anime`); But problem is `category-anime` includes legit streaming services such as crunchyroll and funimation and in some instance that someone uses `category-piracy` to block them, those will be blocked too.

I opened this issue to know the maintainers insight about it and if merging such a fork will be accepted so I don't waste time on it.

**Comment by rootmelo92118** [comment]
Actually the issue https://github.com/v2fly/domain-list-community/issues/390 disscussed this before. It has some complicate course that is not easy to say. As a result, https://github.com/Loyalsoldier/domain-list-custom can help you.
