### ISSUE TITLE
Create a command-line tool to help reading the content of `geosite.dat` and `geoip.dat`

### ISSUE THREAD

**Issue by Benyamin-Tehrani** [v2fly/domain-list-community#1887]
`geosite.dat` and `geoip.dat` are not able to read after generated. I think some kind of tool is needed to help reading and processing them.
It can be named as something like: `geoutils`，provide some commands like:
- Search through the file: `geoutils geosite.dat -s/--search google.com`, show results found and its categories
- List all categories: `geoutils geosite.dat -l/--list`
- List content of any category: `geoutils geosite.dat -l/--list category-dev`

If abilities like add/remove/move category can be supported, it will be better.

**Comment by Loyalsoldier** [comment]
Yeah, will provide such features sooner or later.
