### ISSUE TITLE
the test-ipv6 is no use, could someone help with it?

### ISSUE THREAD

**Issue by czg-sci-42ver** [v2fly/domain-list-community#1904]
Instructed by the [official doc](https://www.v2ray.com/en/configuration/routing.html#ruleobject), I originally use the self-defined rules to let "test-ipv6.com" direct connected.
```json
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {   
        "type": "field",
        "outboundTag": "direct",
        "ip": [
...
        ],  
        "domain": [
          "test-ipv6",                                                                                                                                                    
          "ipv6",
          "regexp:\\..*ipv6.*",
          "ipv4",
          "speedtest.cn"
        ]   
      },  
...
```
however, after visiting url "https://www.test-ipv6.com/"
```bash
$ sudo vim /var/log/v2ray/error.log
...
... app/dispatcher: taking detour [proxy] for [tcp:ipv4.lookup.test-ipv6.com:443]
... app/dispatcher: taking detour [proxy] for [tcp:ipv6.lookup.test-ipv6.com:443]
... app/dispatcher: taking detour [proxy] for [tcp:ipv6.ams2.test-ipv6.com:443]
```

Then I followed [this](https://github.com/v2fly/domain-list-community/tree/7f4e8bbb9cadc81b619b31f41a2d6dfb1bf769da#generate-dlcdat-manually) to generate `dlc.dat` and use it
```bash
...
$ go run ./
Use domain lists in ./data
dlc.dat has been generated successfully.
$ grep "test-ipv6" dlc.dat | wc -l
2
$ sudo cp dlc.dat /usr/share/v2ray/
$ ls /usr/share/v2ray/            
dlc.dat  geoip.dat  geosite.dat
```
then I added `"geosite:test-ipv6",` at the related location, but the problem is still there.

Could someone help me with this problem, thanks in advance.

**Comment by Loyalsoldier** [comment]
Which version of V2Ray are you using?

**Comment by czg-sci-42ver** [comment]
> Which version of V2Ray are you using?

Thanks for your answer.

when I posted this issue, I use:
```bash
$ sudo systemctl status v2ray.service
...
V2Ray 5.6.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.20.4 linux/amd64)
...
```

after updating to `5.9.0` hinted by your comment, the problem is still there.

**Comment by Loyalsoldier** [comment]
You are using V2Ray v4 configuration, but it has been changed in V2Ray v5 version. More details here: https://www.v2fly.org/v5/config/router.html

BTW, the official website is https://www.v2fly.org
