### ISSUE TITLE
ea游戏平台（Origin）域名添加建议

### ISSUE THREAD

**Issue by Jaxes** [v2fly/domain-list-community#192]
origin.com
ea.com
akamaihd.net

rtm.tnt-ea.com
cloudsync-prod.s3.amazonaws.com

**Comment by blessingCN** [comment]
> akamaihd.net
这个域名是 akamai cdn 的域名

**Comment by KevinZonda** [comment]
> > akamaihd.net
> 
> 这个域名是 akamai cdn 的域名

See here 

https://github.com/v2fly/domain-list-community/blob/594d543e89442a104093c0a9e41f26cfddb932a8/data/akamai#L42

**Comment by Robot-DaneelOlivaw** [comment]
感谢建议，欢迎继续提报issue或提交PR。

**Comment by AdoShan** [comment]
> 

大佬，知道tnt-ea.com主要是干嘛的嘛
