### ISSUE TITLE
direct access to Iran (.ir) sites and domains

### ISSUE THREAD

**Issue by Farzadlatifeh** [v2fly/domain-list-community#1969]
it seems geoip:.ir and geosite:.ir doesn't work in whitelist, any suggestion would be appreciated.

**Comment by lxl66566** [comment]
try `geosite:category-ir`

**Comment by Loyalsoldier** [comment]
It's `geoip:ir`, not `geoip:.ir`

**Comment by Farzadlatifeh** [comment]
@Loyalsoldier and @lxl66566 Non of the above solutions have worked
