### ISSUE TITLE
Please add msftconnecttest.com to microsoft file

### ISSUE THREAD

**Issue by MiladRezaeian** [v2fly/domain-list-community#1983]
Please add msftconnecttest.com to microsoft file, when Skype app started to work communicate with this domain

here:
https://github.com/v2fly/domain-list-community/blob/master/data/microsoft

**Comment by Loyalsoldier** [comment]
It's in `private` list: https://github.com/v2fly/domain-list-community/blob/cb227a38117cfc6fe0c50a34f05d6deffde6f4cc/data/private#L182-L184
