### ISSUE TITLE
Can't use .dat file with custom data set

### ISSUE THREAD

**Issue by neerro** [v2fly/domain-list-community#1990]
Hi there domain list community developers. 
Thanks for your hard and necessary work.
I met some issue and would like to discuss it.

I did everything as per **Generate dlc.dat manually** on Ubuntu 22.04, but when I generate .dat file including custom data file (which was added using nano editor) I can't use in v2ray rules it doesn't work for me. Please explain what I'm doing wrong as I tried add any repo data file is already included in data dir rules and it's work correct.

**Comment by rootmelo92118** [comment]
Could you post the error message?
