### ISSUE TITLE
README 中关于 attr 的介绍是否需要更新呢？

### ISSUE THREAD

**Issue by IceCodeNew** [v2fly/domain-list-community#202]
刚瞄了一眼导出来的大类下完整域名条目，注意到 attr 标记是
`domain:st.dl.pinyuncloud.com:@cn` 这样的形式，
`domain:st.dl.pinyuncloud.com @cn` <- 而不是 README 中介绍的这种形式。

https://github.com/IceCodeNew/domain-list-community/blob/release/category-entertainment.txt

**Comment by Loyalsoldier** [comment]
原则上，导出的列表并不面向用户，也不宣传。`:` 形式是为了方便进行文本处理。

**Comment by IceCodeNew** [comment]
> 原则上，导出的列表并不面向用户，也不宣传。`:` 形式是为了方便进行文本处理。

我明白，PR #116 的讨论我还没有忘记。
但是我觉得这部分内容如果还没有从 README 上删掉的话，那有错误的地方也还是可以考虑修正一下。
毕竟这个地方的错误影响的不是在配置里用 `@attr` 的用户，而是 PR 时打算给域名标记 attr 的贡献者……

**Comment by Loyalsoldier** [comment]
没太懂你的意思，README 有错误？

**Comment by Robot-DaneelOlivaw** [comment]
https://github.com/v2fly/domain-list-community/blob/89c441b252b9fb5c87dbb54d7c48318e842a9a72/main.go#L52
`:`是在导出列表时才加上去的，平时添加`@attr`时按照README里的格式就可以了。

**Comment by IceCodeNew** [comment]
> https://github.com/v2fly/domain-list-community/blob/89c441b252b9fb5c87dbb54d7c48318e842a9a72/main.go#L52
> 
> 
> `:`是在导出列表时才加上去的，平时添加`@attr`时按照README里的格式就可以了。

懂了，感谢。
