### ISSUE TITLE
是否应将 .moe 域名移出 tld-!cn？

### ISSUE THREAD

**Issue by MoetaYuko** [v2fly/domain-list-community#2042]
理由同 https://github.com/v2fly/domain-list-community/issues/1606

https://github.com/v2fly/domain-list-community/commit/b5db9c05e5ae83ccc59ebb75be3263195f5d80c6 @Loyalsoldier

**Comment by rootmelo92118** [comment]
PR is welcome

**Comment by Loyalsoldier** [comment]
.moe 并不在工信部的可备案顶级域名列表里。不可备案，意味着其服务器不可能位于中国大陆。

**Comment by MoetaYuko** [comment]
> .moe 并不在工信部的可备案顶级域名列表里。不可备案，意味着其服务器不可能位于中国大陆。

用作 ddns 域名就位于大陆了，且不存在备案问题

**Comment by rootmelo92118** [comment]
> > .moe 并不在工信部的可备案顶级域名列表里。不可备案，意味着其服务器不可能位于中国大陆。
> 
> 用作 ddns 域名就位于大陆了，且不存在备案问题

該理由不成立，那照你這麼說所有域名都可以透過ddns 映射回中國大陸，那這個列表就沒有存在的必要了，但ddns 作為小眾解決方式，他不符合大部分的情況，而本刺更改會影響到大多數的情境，所以將在稍後回退。

**Comment by rootmelo92118** [comment]
附註，我建議你使用geoip:can來解決該問題

**Comment by MoetaYuko** [comment]
ddns 只是一个例子。移出 tld-!cn 的主要原因是该 TLD 并非某个国家/地区所有，而是面向全球开放注册的。当然从备案的角度来讲可能无法“合法”地指向大陆服务器？除此之外与 .me 这类 TLD 没有区别

不知【不能备案】是否意味着 TLD 必须进入 tld-!cn？是的话就 revert 吧

**Comment by KukiSa** [comment]
`tld-!cn` 应当与 `tld-cn` 对应，后者为工信部的可备案顶级域名列表，实践中一般会将后者设置为 `direct` 而非将前者设为 `proxy`，在 `.moe` 未被列入工信部的可备案顶级域名列表前，将其修出 `tld-!cn` 应当是不合适的。

另外，`tld-!cn` 中不少域名是公开注册且均能够自由地解析，「可公开注册」和「能够解析到中国大陆」与是否被列入 `tld-!cn` 无关。

**Comment by KukiSa** [comment]
https://github.com/v2fly/domain-list-community/commit/d59e0d47c14f390a88e41a203a9352af662aa5d5 将 `tld-!cn` 修出 `geolocation-!cn` 无疑是解决问题的合理方法。
