### ISSUE TITLE
能否直接输出特定类目中的域名

### ISSUE THREAD

**Issue by shrugginG** [v2fly/domain-list-community#2115]
根据我的理解domain-list-community的作用是增强v2ray分流的第三方数据库。但我当前的需求并不是直接在v2ray中使用，而是直接基于domain-list-community得到指定公司或组织中的域名列表。例如"geosite:google"会让v2ray对谷歌的相关域名采取指定的代理规则，而我需要直接输入google得到google的相关域名。我观察到dat文件是无法以类似于text形式直接读取的，应该是由v2ray的相关功能负责解析。想请教一下有没有类似于运行go的一条命令行或者简单的编程就可以实现上述需求，或者直接提取v2ray的相关实现的源码。

**Comment by rootmelo92118** [comment]
go run ./ --exportlists=google
