### ISSUE TITLE
Missing `apps.apple.com` domain in `apple` list

### ISSUE THREAD

**Issue by qupig** [v2fly/domain-list-community#2176]
https://github.com/v2fly/domain-list-community/blob/b6a5948cf930ff4078467374948d70548bae4b6a/data/apple#L797-L800

Here, I agree with the #503 change, but after removing `@cn`, the domain `apps.apple.com` should still remain in the `apple` list shouldn't it?

The current situation is that the domain name is not included in the `apple` list at all, but the domain name does belong to `apple`, doesn't it?

**Comment by database64128** [comment]
The top-level `apple.com` domain name is already in the list, and covers its subdomains.
