### ISSUE TITLE
请解释一下gfw清单

### ISSUE THREAD

**Issue by SESProMax** [v2fly/domain-list-community#2316]
请问gfw这个表项在哪里？我设置了geosite:gfw，但我查本项目列表里没找到gfw项。另外docker也不能访问了，可以拉进黑名单。

**Comment by 52comfortable** [comment]
官方库并没有gfw，你说的这个是第三库的
![image](https://github.com/user-attachments/assets/2f7dcb42-d146-4db9-820a-d4bc28e96e3b)
https://github.com/Loyalsoldier/domain-list-custom
