### ISSUE TITLE
microsoft分类下这几行是不是有错误？

### ISSUE THREAD

**Issue by ixff** [v2fly/domain-list-community#2343]
在项目README里没有找到相关的说明

https://github.com/v2fly/domain-list-community/blob/d7dfd191e013efd6cf08ed0b60e2bd33c92f6577/data/microsoft#L10-L20

**Comment by Loyalsoldier** [comment]
没错

**Comment by KukiSa** [comment]
以上均为 Microsoft Corporation 所获分配的顶级域 (Top Level Domain).

https://www.iana.org/domains/root/db/microsoft .html
https://www.iana.org/domains/root/db/hotmail.html
https://www.iana.org/domains/root/db/office.html
https://www.iana.org/domains/root/db/skype.html
