### ISSUE TITLE
attr 类型没有被正确处理

### ISSUE THREAD

**Issue by kslr** [v2fly/domain-list-community#235]
https://github.com/v2fly/domain-list-community/blob/release/geolocation-!cn.txt#L3993

!cn 也包含了 @cn 的结果

cc @Loyalsoldier @Robot-DaneelOlivaw @EpLiar

**Comment by kslr** [comment]
ref https://github.com/shadowsocks/shadowsocks-windows/issues/2971

**Comment by Robot-DaneelOlivaw** [comment]
这个处理应该是正确的，`@cn`指的是在中国大陆有接入点，`geolocation-!cn`域名也适用。我也有在路由规则中用到`geosite:geolocation-!cn@cn`。

**Comment by studentmain** [comment]
地理位置既不在也在中国？

**Comment by Nukme** [comment]
对于ss用户来说如何学习利用geosite规则？ 

ss只有一个一键生成pac（无法控制生成细则，比如是否区分cn），和一个用abp语法的user-rule。这种情况下除了单独写例外有什么好方法吗？

**Comment by KevinZonda** [comment]
> 
> 
> 地理位置既不在也在中国？

可能是指在中国有节点，但是主题域名不在内地。

**Comment by Robot-DaneelOlivaw** [comment]
> 地理位置既不在也在中国？

情况是这样的：`geolocation-!cn`依据列表实体的地理位置进行归类，如苹果公司、微软公司、Valve属于美国企业，则`apple`、`microsoft`、`steam`归类于`geolocation-!cn`。然而三者都有不少的域名在中国大陆存在接入点，又鉴于本项目的宗旨是不声明或暗示某一域名是否应该被代理，因此根据 #91 达成的共识，采用`@cn`对这类特例进行了标记，用户可以在路由规则中进行特殊处理，增加配置的灵活度。

然而这一功能争议较大、尚未完善、且如`google`等域名接入点情况容易产生变动，所以没有对这一功能进行宣传，仅供熟悉项目的人士测试使用。如果希望为游戏下载、应用商店下载、系统更新进行分流，可以尝试。

> 对于ss用户来说如何学习利用geosite规则？

似乎自 #215 起开始生成新文件供其它项目使用了？缓兵之计或许是在生成文件时去除标记有`@cn`的域名。但`geolocation-!cn`与`gfwlist`的定位似乎相差较大。

P.S. 长远来说，我认为一种理想情况是针对所有域名的接入点进行标记，如`@cn`、`@!cn`甚至`@us`、`@hk`、`@sg`等，这样就能提供比`geolocation-cn`、`geolocation-!cn`高得多的精确度和灵活度，可以采用 #54 的提议进行部分自动化标记工作。当然，对工作量的要求或许过高了。

**Comment by Loyalsoldier** [comment]
Will be fixed by https://github.com/v2fly/domain-list-community/pull/236

**Comment by database64128** [comment]
shadowsocks/shadowsocks-windows#2982 excludes `@cn` from the generated `pac.txt`.
