### ISSUE TITLE
新版本PAC会代理局域网地址和内部自定义域名

### ISSUE THREAD

**Issue by HiroC222** [v2fly/domain-list-community#257]
[新版本PAC会代理局域网地址 #3002](https://github.com/shadowsocks/shadowsocks-windows/issues/3002#issue-728143134) 

环境
Shadowsocks客户端版本：4.3.0.0

希望能默认过滤掉局域网地址，内部自定义域名

**Comment by Loyalsoldier** [comment]
本项目没有与 IP 地址相关的规则。
