### ISSUE TITLE
cn.bing.com怎么不在列表里了

### ISSUE THREAD

**Issue by k79e** [v2fly/domain-list-community#260]
好像以前都有啊

反正今天发现是不走direct了
关键就是我看data里面那个bing文件最近就没修改啊 而我最近更新了新版本之后发现不对劲了

发现是在这里的时候那个记录就不见了
https://github.com/v2fly/domain-list-community/commit/983b60497a3e32d945c203ff52c2a0496043bc51
https://github.com/v2fly/domain-list-community/commit/f59afd97019d5aa9ec24ffb732908c2e4c5f0666#diff-899344237445ec1c576b5d6ec26dc46d51c664fb986306a4efdeb29bd49915fa

666结尾的地方就消失了 但是diff没显示
https://github.com/v2fly/domain-list-community/blob/983b60497a3e32d945c203ff52c2a0496043bc51/data/geolocation-cn
https://github.com/v2fly/domain-list-community/blob/f59afd97019d5aa9ec24ffb732908c2e4c5f0666/data/geolocation-cn

**Comment by Loyalsoldier** [comment]
可以在配置文件中增加 `geosite:bing@cn` 走 direct：

```json
{
        "type": "field",
        "outboundTag": "direct",
        "domain": [
          "geosite:bing@cn"
        ]
},
```

**Comment by k79e** [comment]
但是他为什么不算cn域名了?

**Comment by Loyalsoldier** [comment]
都规整到各自的列表里了。

目前的缓解方案是：

```json
{
        "type": "field",
        "outboundTag": "direct",
        "domain": [
          "geosite:geolocation-!cn@cn"
        ]
},
```

**Comment by k79e** [comment]
啊 原来是用法变了....

**Comment by Loyalsoldier** [comment]
没变，只是域名换了位置，导致默认会走代理。
