### ISSUE TITLE
希望能在 Release 中输出一份 cn 域名

### ISSUE THREAD

**Issue by CalmLong** [v2fly/domain-list-community#263]
如题

自己写程序输出的话需要引入 V2Ray core，希望能输出一份 `cn`  域名让其他程序调用

**Comment by IceCodeNew** [comment]
> 如题
> 
> 自己写程序输出的话需要引入 V2Ray core，希望能输出一份 `cn` 域名让其他程序调用

fork 这个项目，根据自己需要修改 GitHub workflow 文件即可。

参考实现：https://github.com/IceCodeNew/domain-list-community/commit/73954e65aefb1158eb9149f0a787a8e87da246d1

**Comment by Loyalsoldier** [comment]
release 分支有 `cn` 文件所包含的规则（域名、正则、关键词）：https://github.com/v2fly/domain-list-community/blob/release/cn.txt
