### ISSUE TITLE
gstatic.com被墙

### ISSUE THREAD

**Issue by wancaibida** [v2fly/domain-list-community#267]
不代理gstatic.com的情况下， 能打开Google drive登录界面，但是点击登录没反应，查看控制台发现`gstatic.com` 提示 `Unable to establish SSL connection`。

**Comment by KevinZonda** [comment]
好奇怪w

https://github.com/v2fly/domain-list-community/blob/f29ec97f5a49c421d78cbf34802512612521edd8/data/google#L386

**Comment by wancaibida** [comment]
找到原因了，我用的是 Loyalsoldier的 [geosite.dat](https://github.com/Loyalsoldier/v2ray-rules-dat/blob/release/direct-list.txt#L25790) 的，它里面是直连的：
![Screen Shot 2020-11-13 at 10 54 43](https://user-images.githubusercontent.com/5710237/99023121-ea3f2780-259e-11eb-9fd6-bc1d6e6ca2c2.png)
