### ISSUE TITLE
Remove `@cn` from `gstatic.com`

### ISSUE THREAD

**Issue by database64128** [v2fly/domain-list-community#271]
The CDNs of `gstatic.com` in Mainland China don't serve the same content as the international ones. This causes issues when using some of Google's services.

### Steps to replicate

1. Add a rule to use direct connection for `domain:gstatic.com`.
2. Use your phone's browser to google something that has an AMP preview.
3. Tap on the link to the preview. The page shows a 404 error.
4. Remove the rule added in step 1. Make sure you don't have any other rules that interfere with the experiment.
5. Tap on the same link. The AMP preview now loads.

### Related issues

A user of shadowsocks-windows has also found it to be causing issues with Google's translation service: shadowsocks/shadowsocks-windows#3028.

The Chinese CDNs of `gstatic.com` is basically enforcing censorship. They don't serve the same content, and therefore can't be treated as Chinese access points of `gstatic.com`. The `cn` tag on these domain names should be removed.

**Comment by kslr** [comment]
I’d be willing to review a PR if you want to contribute a fix.

**Comment by annaberdiyewaly42-create** [comment]
https://script.google.com/macros/s/AKfycbx8oXGhm2Fg5K40f4XH7UrMsj1DSD6YSnOAvZv94scjhC59G0qpmYntmVDMyy4pfluyoQ/exec?url=https://oglan-tm.ru:2087/sub/RG50ciwxNzU1NjM2NDkyU-zVyVITrF

**Comment by annaberdiyewaly42-create** [comment]
https://script.google.com/macros/s/AKfycbx8oXGhm2Fg5K40f4XH7UrMsj1DSD6YSnOAvZv94scjhC59G0qpmYntmVDMyy4pfluyoQ/exec?url=https://oglan-tm.ru:2087/sub/RG50ciwxNzU1NjM2NDkyU-zVyVITrF

**Comment by annaberdiyewaly42-create** [comment]
[https://script.google.com/macros/s/AKfycbx8oXGhm2Fg5K40f4XH7UrMsj1DSD6YSnOAvZv94scjhC59G0qpmYntmVDMyy4pfluyoQ/exec?url=script

**Comment by annaberdiyewaly42-create** [comment]
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpZQTA3UjBEYXVsdWlQa0hrbV96Q2V3@91.223.236.174:31#%F0%9F%87%B9%F0%9F%87%B2RAHYM+SERVICE+VPN
