### ISSUE TITLE
[提议]建议加入专门针对教育网的列表

### ISSUE THREAD

**Issue by dqwfgzs** [v2fly/domain-list-community#301]
便于教育网用户合理使用上网流量（如一些高校允许IPv6免费使用）

**Comment by IceCodeNew** [comment]
教育网的免费地址列表只有 IP，没有域名，你可能需要 fork geoip 项目做自己的修改。
免费地址列表：
http://www.nic.edu.cn/RS/ipstat/internalip/
http://www.nic.edu.cn/RS/ipstat/internalip/somepeers.txt
