### ISSUE TITLE
geoip:ir didnt work

### ISSUE THREAD

**Issue by sae13** [v2fly/domain-list-community#315]
hi there I tried to bypass iran ips with advance route setting.
but it only works if i put sites in domain cell not ip cell
![only axbabak.ir will bypass](http://axbabak.ir/uploads/7286Screenshot-from-2020-12-15-11-17-28.png)

**Comment by DuckSoft** [comment]
Domain Strategy: AsIs -> IPIfNonMatch

**Comment by DuckSoft** [comment]
Read the docs:
- Qv2ray: https://qv2ray.net/en/manual/route.html#global-routing-rules
- V2Fly: https://www.v2fly.org/config/routing.html#routingobject (in Chinese, sadly there's no English version)

**Comment by sae13** [comment]
didnt work 
![](https://axbabak.ir/uploads/7aa1Screenshot-from-2020-12-15-11-45-00.png)

**Comment by DuckSoft** [comment]
add domain:ir to (domain, direct)

**Comment by sae13** [comment]
thanks works with domains. but why does not works with ips?
how i can say proxy all except these ips?

**Comment by DuckSoft** [comment]
you should read the docs more carefully (though it's in Chinese).
if no domain rules are matched and the strategy is IPIfNonMatch, the requested domain will go through V2Ray DNS Resolution process. The returned IP addresses are matched against IP rules then. It could be:
- either V2Ray DNS does not resolve your domain correctly. 
- or geoip:ir does not include your target IP

**Comment by NightMachinary** [comment]
[**@DuckSoft**](https://github.com/DuckSoft) commented on [Dec 15, 2020, 12:03 PM GMT+3:30](https://github.com/v2fly/domain-list-community/issues/315#issuecomment-745137114 "2020-12-15T08:33:24Z - Replied by Github Reply Comments"):
> you should read the docs more carefully (though it's in Chinese).  
> if no domain rules are matched and the strategy is IPIfNonMatch, the requested domain will go through V2Ray DNS Resolution process. The returned IP addresses are matched against IP rules then. It could be:
> 
> *   either V2Ray DNS does not resolve your domain correctly.
> *   or geoip:ir does not include your target IP
> 
> It's complicated and very tedious to expand. Read the docs.

My main outbound proxy doesn't support UDP and DNS. Can I make some outbound that is only used for DNS?
