### ISSUE TITLE
update.googleapis.com wrongly tagged with 'cn' attribute

### ISSUE THREAD

**Issue by ziruizhuang** [v2fly/domain-list-community#360]
### Environment
Shadowsocks client version: 4.4.0.0, prefer direct mode.
OS version: Windows 10 20H2
.NET version:
### Steps you have tried
Check update in Google Chrome.

### What did you expect to see?
Successfully checking and updating Google Chrome

### What did you see instead?
Checking failed.
An error occurred while checking for updates: Unable to connect to the Internet. If you use a firewall, please whitelist GoogleUpdate.exe
Error code 0x80072F7D

Gone through the traffic logs and found out a possible cause:
Domain 'update.googleapis.com' is with 'cn' attribute in DLC data. While in fact 'update.googleapis.com' is not reachable directly.

[shadowsocks/shadowsocks-windows#3065](https://github.com/shadowsocks/shadowsocks-windows/issues/3065)

**Comment by IceCodeNew** [comment]
`update.googleapis.com` does point to a server in China. If you are having trouble accessing this domain, you should append `update.googleapis.com` into `user-rule.txt`.
This project does not make it convenient for the purposes of your use case nor shadowsocks-windows.

![image](https://user-images.githubusercontent.com/32576256/104157412-0e47a980-5426-11eb-9712-0845f5429e02.png)
