### ISSUE TITLE
`screenrant-com.cdn.ampproject.org` does not point to a server located in China.

### ISSUE THREAD

**Issue by wd** [v2fly/domain-list-community#374]
The domain can't be visited in China
https://github.com/v2fly/domain-list-community/blob/f7a7c07c46b304ca56809b52728ba5226d8ef315/data/amp#L6

**Comment by IceCodeNew** [comment]
![image](https://user-images.githubusercontent.com/32576256/105003499-b1737100-5a6d-11eb-8f57-171640d581bf.png)

**Comment by IceCodeNew** [comment]
`# dig @223.5.5.5 cdn.ampproject.org cname +short`
> cdn-china.ampproject.org.

**Comment by Loyalsoldier** [comment]
根据 [https://github.com/felixonmars/dnsmasq-china-list/issues/281](https://github.com/felixonmars/dnsmasq-china-list/issues/281) 似乎解析到大陆确实有问题。

**Comment by wd** [comment]
Sorry I made a mistake. The domain `cdn.ampproject.org` can be resolved to an IP in China. but the domain like `screenrant-com.cdn.ampproject.org` can't. 

```
dig +short @114.114.114.114 screenrant-com.cdn.ampproject.org
cdn-content.ampproject.org.
172.217.27.129
```

**Comment by IceCodeNew** [comment]
> Sorry I made a mistake. The domain `cdn.ampproject.org` can be resolved to an IP in China. but the domain like `screenrant-com.cdn.ampproject.org` can't.
> 
> ```
> dig +short @114.114.114.114 screenrant-com.cdn.ampproject.org
> cdn-content.ampproject.org.
> 172.217.27.129
> ```

Affirmative. PR welcomed.

**Comment by IceCodeNew** [comment]
Seems the case of accessing `screenrant-com.cdn.ampproject.org` is already covered:

https://github.com/v2fly/domain-list-community/blob/ce545cd1fe4f811e73db5549229d3991ca5f5409/data/amp#L4-L6

**Comment by wd** [comment]
Yeah, I have seen that. I don't know what does the `full` mean. Does that mean an equal match?

For my use cases, I use `geosite:cn` to filter out all the domains that I don't want to use the proxy as bellow.
```
     {
                                "type": "field",
                                "domain": [
                                        "geosite:cn"
                                ],
                                "outboundTag": "direct"
                        },
```
It will cause domains like `screenrant-com.cdn.ampproject.org` didn't use the proxy. So it can't be connected.

**Comment by IceCodeNew** [comment]
> I don't know what does the `full` mean. Does that mean an equal match?

`full:cdn.ampproject.org` will only match domain `cdn.ampproject.org` exactly, `screenrant-com.cdn.ampproject.org` won't match.

---

> For my use cases, I use `geosite:cn` to filter out all the domains that I don't want to use the proxy as bellow.
> 
> ```
>      {
>                                 "type": "field",
>                                 "domain": [
>                                         "geosite:cn"
>                                 ],
>                                 "outboundTag": "direct"
>                         },
> ```
> 
> It will cause domains like `screenrant-com.cdn.ampproject.org` didn't use the proxy. So it can't be accessed.

Then `screenrant-com.cdn.ampproject.org` will not use `direct` outbound unless there is something other that will match this domain.

**Comment by wd** [comment]
That's weird, I have to put these lines just before the `geosite:cn` to get it working 
```
                        {
                                "type": "field",
                                "domain": [
                                        "ampproject.org"
                                ],
                                "outboundTag": "proxy"
                        },
```

**Comment by Loyalsoldier** [comment]
> That's weird, I have to put these lines just before the `geosite:cn` to get it working
> 
> ```
>                         {
>                                 "type": "field",
>                                 "domain": [
>                                         "ampproject.org"
>                                 ],
>                                 "outboundTag": "proxy"
>                         },
> ```

Are you using my project `https://github.com/Loyalsoldier/v2ray-rules-dat` as the source of `geosite.dat`?

**Comment by wd** [comment]
Oh, sorry about that. I'm using another one generated based on this one. You are right; I should probably test against this one. I'll update this issue after the tests. Thanks.

**Comment by Loyalsoldier** [comment]
Oh, if you're using my project or the forked ones, that's the problem. I removed the `full:` prefix of all domains. So it will match `cdn.ampproject.org` and all its sub-domains.

**Comment by IceCodeNew** [comment]
> Oh, if you're using my project or the forked ones, that's the problem. I removed the `full:` prefix of all domains. So it will match `cdn.ampproject.org` and all its sub-domains.

What is that for to remove the `full:` prefix?

**Comment by Loyalsoldier** [comment]
> > Oh, if you're using my project or the forked ones, that's the problem. I removed the `full:` prefix of all domains. So it will match `cdn.ampproject.org` and all its sub-domains.
> 
> What is that for to remove the `full:` prefix?

Just for convenience. I will fix it soon.

**Comment by Loyalsoldier** [comment]
Fixed https://github.com/Loyalsoldier/v2ray-rules-dat/commit/18f0a8301a4e97d74acbe385f3c30f0e8c4057d4
