### ISSUE TITLE
[讨论] 对于分类、组和单项，不再要求按照首字母排列

### ISSUE THREAD

**Issue by kslr** [v2fly/domain-list-community#386]
理由： 对同一个企业下不同的子公司/部分组织更加清晰

**Comment by DuckSoft** [comment]
应该可以用缩进来区分？
举个例子：
```
aa
bb
cc
  aa-of-cc
  bb-of-cc
  cc-of-cc
dd
ee
ff
gg
  aa-of-gg
  bb-of-gg
  cc-of-gg
```

**Comment by kslr** [comment]
缩进破坏就比较大了吧，成本也比较高。注释大概就够用了
```
# google
google.com

# google email
gmail.google.com
```

**Comment by IceCodeNew** [comment]
> 缩进破坏就比较大了吧，成本也比较高。注释大概就够用了
> 
> ```
> # google
> google.com
> 
> # google email
> gmail.google.com
> ```

我觉得这个不就是答案了吗
只要求局部有序就可以了，不同子公司之间用注释区隔，然后每个小区隔内做到字典序排序就好了。

**Comment by kslr** [comment]
> > 缩进破坏就比较大了吧，成本也比较高。注释大概就够用了
> > ```
> > # google
> > google.com
> > 
> > # google email
> > gmail.google.com
> > ```
> 
> 我觉得这个不就是答案了吗
> 只要求局部有序就可以了，不同子公司之间用注释区隔，然后每个小区隔内做到字典序排序就好了。

外面也需要，因为这样 attr 好打一点

**Comment by IceCodeNew** [comment]
> > 只要求局部有序就可以了，不同子公司之间用注释区隔，然后每个小区隔内做到字典序排序就好了。
> 
> 外面也需要，因为这样 attr 好打一点

没 get 到，你能举个例子吗？

**Comment by kslr** [comment]
> > > 只要求局部有序就可以了，不同子公司之间用注释区隔，然后每个小区隔内做到字典序排序就好了。
> > 
> > 
> > 外面也需要，因为这样 attr 好打一点
> 
> 没 get 到，你能举个例子吗？

不管是移除分类或者保留分类，以单位和attr类组织

**Comment by phlinhng** [comment]
有些現有條目的排序是亂的，是否需要統一修正？例如這條
https://github.com/v2fly/domain-list-community/blob/9fe5d10a72698a3af215785454baa83261c1acdf/data/bahamut#L1-L4
