### ISSUE TITLE
新增 services.googleapis.cn 进入黑名单，让其走代理。

### ISSUE THREAD

**Issue by zw963** [v2fly/domain-list-community#398]
华为手机，在配置完成 Google 全家桶之后，进入 Play 上面，无法安装任何 app, 总是提示： ”正在等待", 但是同时，Youtube 可以看视频，解决这个问题的方案是，增加  services.googleapis.cn 到 V2ray 透明代理的黑名单，让它走翻墙，修复！

不知道本项目是否有类似功能？ 我的建议是，不可以所有的 .cn 域名一刀切，全部走直连，谢谢。

**Comment by IceCodeNew** [comment]
![image](https://user-images.githubusercontent.com/32576256/107253804-aa8abd80-6a71-11eb-8f30-23b36bdc6534.png)

**Comment by IceCodeNew** [comment]
众口难调，请不要总是拿自己的使用场景要求修订域名分类
添加自定义规则解决实际问题才是正确做法
或者考虑使用下游的其他“增强版” geosite 发布

**Comment by zw963** [comment]
@IceCodeNew , 抱歉，我增加这个 issue, 是因为我刚刚和 https://github.com/felixonmars/dnsmasq-china-list 这个项目的维护者，在 Arch 群里聊了几句，他帮正是建议我加上面的网址到黑名单，解决了这个华为手机的问题, 并且，他说 ”这确实是一个古老的问题了“，而他作为长期域名维护者，自然比较可信，所以，我不认为这是只有我个人才会遇到的问题，才提了这个 issue.

![image](https://user-images.githubusercontent.com/549126/107257856-166f2500-6a76-11eb-875e-7b2a43063e35.png)

根据你的测试结果，我只能猜测，这个域名可能返回的内容都是假的，因此才会 block 华为手机下载的流程。

**Comment by database64128** [comment]
My solution is to simply add a rule to use proxy for `geosite:google`. Hope this helps with your problem.

**Comment by IceCodeNew** [comment]
> 
> 
> My solution is to simply add a rule to use proxy for `geosite:google`. Hope this helps with your problem.

+1

**Comment by Zeehan2005** [comment]
个人意见，看上去需要使用谷歌中国业务的人似乎极少，而需要使用Google Play的人相当多。既然重口难调，那为什么不直接参考大多数人的选择并让少数人自行配置呢？
