### ISSUE TITLE
申请对该 repo 的写权限

### ISSUE THREAD

**Issue by IceCodeNew** [v2fly/domain-list-community#47]
如题，经历了数次成功的 commit，兼读过了 Issue #28 的讨论后，我有了些信心参与到该项目的管理中。

祝好。

**Comment by EpLiar** [comment]
稍微等一下，编译炸了

**Comment by IceCodeNew** [comment]
看了一眼 log，`mmap: bad file descriptor`

GitHub 土豆服务器怕不是又炸了……

**Comment by EpLiar** [comment]
已发送邀请

**Comment by IceCodeNew** [comment]
谢谢
