### ISSUE TITLE
[提议]规则加入跨境电商的常用域名

### ISSUE THREAD

**Issue by Jason59533** [v2fly/domain-list-community#494]
韩国电商coupang禁止中国大陆IP访问
shopee各个站点走代理似乎更快
lazada平台能检测到是否使用代理，代理不让访问
wish也是代理更快

**Comment by Loyalsoldier** [comment]
PR is welcome.

**Comment by Loyalsoldier** [comment]
Fixed by https://github.com/v2fly/domain-list-community/pull/524
