### ISSUE TITLE
GitHub workflow failed on Linux x86_64 because of starlark-go

### ISSUE THREAD

**Issue by Loyalsoldier** [v2fly/domain-list-community#52]
GitHub Actions `mmap: bad file descriptor` error caused by starlark-go, details in here: https://github.com/google/starlark-go/pull/297

Failed run here: https://github.com/v2fly/domain-list-community/runs/901018798

**Comment by IceCodeNew** [comment]
[PR #297](https://github.com/google/starlark-go/pull/297) 刚合了，我现在去合并一个我觉得没有问题的 PR，触发 GitHub Actions，看看 workflow 是否能正常工作。
