### ISSUE TITLE
ipv6访问谷歌学术

### ISSUE THREAD

**Issue by chengwei21** [v2fly/domain-list-community#571]
我在ipv6分流中添加了谷歌学术的域名，为什么还是无法访问谷歌学术
![屏幕截图 2021-07-04 084753](https://user-images.githubusercontent.com/53066412/124370322-e6d0eb80-dca8-11eb-8089-003eccf1e1a6.png)
![屏幕截图 2021-07-04 084730](https://user-images.githubusercontent.com/53066412/124370323-e8021880-dca8-11eb-9099-941c4770f1e3.png)

**Comment by IceCodeNew** [comment]
该问题与本项目无关，是用户实际连线到 Google scholar 的 IP 遭到 Google 封锁缘故。
请排查实际连线到 Google scholar 的 IP 是否是用户用来分流的 IPv6 地址，并寻求所使用脚本的开发者帮助。

**Comment by chengwei21** [comment]
好的，谢谢
