### ISSUE TITLE
Disney 域名不全

### ISSUE THREAD

**Issue by BaileyZyp** [v2fly/domain-list-community#572]
我今天使用Disney+的时候不能放视频，发现少了这两个域名
```
bamgrid.com
execute-api.us-east-1.amazonaws.com
```

https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Surge/Disney/Disney.list
可以参考一下这个仓库的域名列表，我不确定是否只少了以上两个

**Comment by IceCodeNew** [comment]
https://github.com/v2fly/domain-list-community/blob/master/data/bamtech#L1

你说的第一条域名项目已经收录了。
第二条域名请先自己验证过（即你需要确保你正确利用了本项目中已经收录的数据，并且确认所提到的域名对于分流 Disney+ 来说是必要的而且本项目没有收录，再来这里汇报（也欢迎直接 PR

**Comment by BaileyZyp** [comment]
![image](https://user-images.githubusercontent.com/16634459/124390335-acedfc80-dd1d-11eb-8d6d-d0a0c61bb415.png)  

我单用'geosite:disney'的时候不能正常访问和观看Disney+

但是我添加了以下规则就可以正常访问，但是我发现列表里面都有
```
"domain:cdn.registerdisney.go.com",
"domain:disneyplus.com",
"domain:disney-plus.net",
"domain:dssott.com",
"domain:bamgrid.com",
"domain:execute-api.us-east-1.amazonaws.com"
```

**Comment by Loyalsoldier** [comment]
上面提到的每个域名都在本项目里，只是需要组合一下。最方便的用法还是 `geosite:geolocation-!cn`
