### ISSUE TITLE
tictok 相关域名被包含在了 "geosite:cn" 列表中

### ISSUE THREAD

**Issue by gosip443** [v2fly/domain-list-community#574]
全局模式下，启用"geosite:cn" 规则时，tiktok 无法访问
全局模式下，取消"geosite:cn" 规则时，tiktok 正常访问

**Comment by maskedeken** [comment]
遇到同样的问题

**Comment by Loyalsoldier** [comment]
把 `geosite:tiktok` 规则放置在 `geosite:cn` 的前（上）面，并设置为走代理即可。
