### ISSUE TITLE
建議拆分 `amazon`

### ISSUE THREAD

**Issue by phlinhng** [v2fly/domain-list-community#580]
由於 amazon 事業龐大，現有的 [`geosite:amazon`](https://github.com/v2fly/domain-list-community/blob/a521895230b280f128255f40c816e15e35968738/data/amazon) 和 [`geosite:amazon-ads`](https://github.com/v2fly/domain-list-community/blob/a521895230b280f128255f40c816e15e35968738/data/amazon) 不足以滿足更細緻的分流需求。

建議比照對 facebook 和 google 域名的做法，將 amazon 域名細分為 `geosite:aws`、`geosite:kindle`、`geosite:primevideo`。

**Comment by IceCodeNew** [comment]
附议，有初步的pr可以link到这个issue上么
