### ISSUE TITLE
建议删除tiktok相关域名，他们在大陆并不可用

### ISSUE THREAD

**Issue by d1478101754** [v2fly/domain-list-community#604]
建议删除tiktok相关域名，他们在大陆并不可用

**Comment by IceCodeNew** [comment]
![image](https://user-images.githubusercontent.com/32576256/129473229-3d406198-b86f-4697-968e-15a561d44237.png)

我检查了一下，目前收录的 tiktok 域名并没有标记 `@cn` 属性，分类文件也没有被包括在普遍被用作大陆服务分流的分类下
——换句话说就是正确使用本项目，这些域名都不会被当作是白名单来用，不应当造成问题

建议你自己排查下手上的工具是如何使用本项目的数据的。删除域名的要求我们不会接受。

**Comment by d1478101754** [comment]
bytedance 里面包括tiktok 所以他被加入cn里了

**Comment by IceCodeNew** [comment]
@Loyalsoldier 我看目前只能把 `geolocation-cn` 里 bytedance 的那行展开了，然后在 bytedance 分类文件里用注释提醒后来的贡献者同步更新 `geolocation-cn`。
你有更好的处理办法么？

**Comment by Loyalsoldier** [comment]
关于这个问题及相似问题，想引入一个 `exclude` 的新语法，但最近还没时间写代码。

建议目前自行配置 `geosite:tiktok` 走代理。

**Comment by jam3ternal** [comment]
现在还是没有修复...

**Comment by IceCodeNew** [comment]
> 建议目前自行配置 geosite:tiktok 走代理。

这个方案不行吗

**Comment by jam3ternal** [comment]
> > 建议目前自行配置 geosite:tiktok 走代理。
> 
> 这个方案不行吗

这个可以, 但是geolocation-cn依然包含tiktok

**Comment by lruLk** [comment]
> > > 建议目前自行配置 geosite:tiktok 走代理。
> > 
> > 
> > 这个方案不行吗
> 
> 这个可以, 但是geolocation-cn依然包含tiktok

我是使用黑名单(因为一般上外网比较多)，然后直接加的 `"geosite:geolocation-!cn"` 给 proxy，那个有`include:category-entertainment` -> `include:tiktok`。同时，我又加了`"geosite:cn"` 给 direct，那个有`include:geolocation-cn` -> `include:bytedance` -> `include:tiktok`。
