### ISSUE TITLE
V2rayN4.20中参数设置直连geosite:category-games@cn但游戏平台没有直连

### ISSUE THREAD

**Issue by STEVEFEN** [v2fly/domain-list-community#629]
我记得一个多月前第一次设置，也是同一个版本4.20，哪时候可以走直连，但现在不知什么时候开始不行了，不知道怎样原因，求指教 @IceCodeNew ，谢谢。

**Comment by IceCodeNew** [comment]
You are spamming here, please stop.

Closed for this issue is duplicated to #618
