### ISSUE TITLE
建议移除elsevier ieee等付费数据库

### ISSUE THREAD

**Issue by moetayuko** [v2fly/domain-list-community#674]
ieeexplore.ieee.org engineeringvillage.com 等数据库本身能正常访问，并且访问权限是跟学校机构付费的ip绑定的，过梯子后网站打开速度可能更快但内容本身就不可见了，没有意义

**Comment by yaott2020-666** [comment]
不建议移除，可以通过这个geosite给国外学术站分流到直连，解决大陆白名单对国外学术站的代理问题
