### ISSUE TITLE
请问能导出为txt吗？想用在AdGuardHome上

### ISSUE THREAD

**Issue by caonima1198** [v2fly/domain-list-community#685]
谢谢。

**Comment by Loyalsoldier** [comment]
可以。

https://github.com/v2fly/domain-list-community/blob/bc2dcda5bff7904afebbeaf8760972e5c0bfd180/.github/workflows/build.yml?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L33
