### ISSUE TITLE
辛苦添加下LG WebOS 里的华数酷喵规则 ，以及对应的Ad规则  感谢

### ISSUE THREAD

**Issue by Leonyeyu** [v2fly/domain-list-community#696]

**Comment by IceCodeNew** [comment]
pr is welcome

**Comment by rootmelo92118** [comment]
@Leonyeyu 請自行提供相關內容或者自行提交pull request.

**Comment by IceCodeNew** [comment]
> @Leonyeyu 請自行提供相關內容或者自行提交pull request.

如果你不能确定提问者是否能使用中文进行交流，建议先用英语和对方沟通喔~

**Comment by rootmelo92118** [comment]
> > @Leonyeyu 請自行提供相關內容或者自行提交pull request.
> 
> 如果你不能确定提问者是否能使用中文进行交流，建议先用英语和对方沟通喔~ @rootmelo92118

這個我知道我是看過了他的儲存庫內容以及這一個issue標題， 而判定對方會說中文。
