### ISSUE TITLE
请问data/zhenqi这样的文件是怎么被使用的？

### ISSUE THREAD

**Issue by alicewww** [v2fly/domain-list-community#702]
[data/zhanqi](https://github.com/v2fly/domain-list-community/blob/master/data/zhanqi)
这个文件里只有一个域名，没有挂诸如@cn的tag，请问这个文件是怎么被使用的？
是只能用于`geosite:zhanqi`这种情况吗？
进一步的，如果我想添加一个属于cn或者不属于cn的域名，请问我是应该添加一个新的文件，还是应该加道`data/geolocation-cn`和`geolocation-!cn`文件呢？

**Comment by IceCodeNew** [comment]
![image](https://user-images.githubusercontent.com/32576256/143220951-b7a4e134-27d3-4f91-8d46-7e613e855999.png)

你可以直接用 `geolocation-cn` 规则，里面包括了这条域名
