### ISSUE TITLE
原来的geosite.dat文件怎么获取？

### ISSUE THREAD

**Issue by yws112358** [v2fly/domain-list-community#704]
是不是项目修改了，记得原来是生成geosite.dat文件，现在是dlc.dat文件了，不会用。下载dlc.dat文件v2rayN直接可以识别吗？
希望能不吝赐教。

**Comment by yaotthaha** [comment]
https://github.com/Loyalsoldier/v2ray-rules-dat

可以试试这个第三方规则，比较全，一直更新

**Comment by Loyalsoldier** [comment]
下载 dlc.dat，把它重命名为 geosite.dat 即可。
