### ISSUE TITLE
询问 爱奇艺国际版站点 iq.com 的处理

### ISSUE THREAD

**Issue by CHIZI-0618** [v2fly/domain-list-community#724]
注意到在 iqiyi 类别中(查了一下此域名并不被包含在任一个类别中)并不包含此域名, 这应该说是正常的. 
此域名在中国大陆可以正常打开但无法进一步打开视频观看, 报来源ip限制. 
![image](https://user-images.githubusercontent.com/51962278/146633311-dbdd18f2-25b7-42a0-bb2b-e3f663e7b1db.png)
如果通过代理访问此域名成功播放视频后, 则可以断开代理改成直连, 如果不刷新网页则可以继续正常观看视频 (此时 iqiyi 类别中的域名和 iq.com 均直连 ). 
上述操作如果使用Clash等代理软件很容易实现, 现在想问*ray系可以做到吗, 或者有其他更好的处理方式?

进一步猜测应该还有其他类似的域名存在此情况.

**Comment by IceCodeNew** [comment]
> 想问*ray系可以做到吗

 你想问的似乎是 v2ray 配置问题，待确定下来现有项目内容无法满足配置需要时，可以带着具体的改进意见再来开 issue 讨论
