### ISSUE TITLE
add discovery+ support?

### ISSUE THREAD

**Issue by happy201807** [v2fly/domain-list-community#760]
没找到discovery+

**Comment by happy201807** [comment]
content-ause1-ur-discovery1.uplynk.com
disco-api.com
discoveryplus.com
fwmrm.net
getblueshift.com
litix.io
mobile-collector.newrelic.com
uplynk.com

**Comment by IceCodeNew** [comment]
@rootmelo92118 有个技巧，可以在提 PR（比如这里是 #924 ）时，在描述信息里写 `fix 
xxx`
这样 pr 合并时会自动关闭相关的 issue
