### ISSUE TITLE
似乎没有对 microsoft-store进行处理？

### ISSUE THREAD

**Issue by chriscp-cat** [v2fly/domain-list-community#766]
microsoft-store 无法正常打开

**Comment by RyzeChang** [comment]
参考 [Qv2ray](https://qv2ray.net/lang/zh/getting-started/step4.html#%E4%BD%BF%E7%94%A8%E7%B3%BB%E7%BB%9F%E4%BB%A3%E7%90%86) 中 Windows 用户：UWP 应用回环问题

**Comment by chriscp-cat** [comment]
谢谢 问题解决了
