### ISSUE TITLE
category-entertainment 修改

### ISSUE THREAD

**Issue by rootmelo92118** [v2fly/domain-list-community#793]
是否需要在此列表中加入大陸的影音娛樂網站？
想了解此合集中的娛樂網站是否有限定大陸境外的域名資料

**Comment by IceCodeNew** [comment]
FYI, Chinese entertainment sites are not collected in a second category like `category-entertainment`, they are directly included in the `geolocation-cn`
<img width="315" alt="image" src="https://user-images.githubusercontent.com/32576256/155690479-9bd21cbf-dfb7-46a9-94fb-9793da8b7726.png">

---

And for the `category-entertainment`, the comment says:
> # This list contains services related to entertainment & games & music & podcasts & videos outside China mainland.
