### ISSUE TITLE
从广告类别中移除log.mmstat.com

### ISSUE THREAD

**Issue by LinaChong** [v2fly/domain-list-community#796]
在adguard的屏蔽列表中, log.mmstat.com是被允许访问的, 屏蔽此网页后淘宝网页端无法正常确认收货。
![Adguard规则](https://user-images.githubusercontent.com/74124808/155988392-e9066e54-e805-4724-8f9c-5e5e40298fc8.png)

**Comment by IceCodeNew** [comment]
该域名并没有被分类到可能被用于广告过滤的类型下。

<img width="920" alt="image" src="https://user-images.githubusercontent.com/32576256/156009265-9d632789-29af-4c90-a0f6-a8a7b50d05ed.png">
