### ISSUE TITLE
游戏《原神》的部分流量在v2ray使用本分流规则时被代理

### ISSUE THREAD

**Issue by Memorywzd** [v2fly/domain-list-community#808]
使用环境：openwrt passwall插件代理，下级设备稳定复现故障
部分问题ip：下列ip识别均为百度识别结果
101.132.253.152 上海市上海 阿里云
47.246.46.225 广东省深圳市 阿里云
58.215.146.121 江苏省无锡市 电信

碍于本人能力有限，只能简单的描述问题出现情况：
某日打游戏时发现界面加载明显过于缓慢，排除若干问题后查看代理日志发现了异常代理流量。由于本人设置openwrt自动更新gfw列表（更新地址 https://cdn.jsdelivr.net/gh/YW5vbnltb3Vz/domain-list-community@release/gfwlist.txt ），猜测是在某次列表更新时误将某域名加入了代理列表。
为何确定是本列表的bug：
换用其它gfw列表（更新地址https://cdn.jsdelivr.net/gh/gfwlist/gfwlist/gfwlist.txt ）后上述ip不再出现于代理流量日志中，游戏正常加载。v2ray修改为“中国列表以外”模式使用clang（https://ispip.clang.cn/all_cn_cidr.txt ）提供的chnroute等未在流量日志中查询到上述ip，游戏正常加载。
提供若干域名关键词谨用于开发大大参考：
原神：yuanshen     genshin      genshin-impact
米哈游：mihoyo

**Comment by IceCodeNew** [comment]
这是第三方问题吧，你应该联系 @YW5vbnltb3Vz/domain-list-community 获取帮助。
