### ISSUE TITLE
CSgo的游戏要怎么加入到路由

### ISSUE THREAD

**Issue by Fengikjing** [v2fly/domain-list-community#827]
我用了GFWlist 不过好像csgo的游戏不在这里面不过csgo需要用这个来加速 不然比较卡，想问一下怎么才能加入

**Comment by IceCodeNew** [comment]
你对游戏卡的描述不详细，帮不上你。
甚至你连这个是联机问题还是游戏资源下载问题都没说清楚，是指望别人叫魂来问清楚吗？
如果是联机问题，通常和域名列表无关，请排查代理实现。如果是游戏资源问题，带上 **脱敏** 后的日志和详细问题描述去 **你用的代理软件的代码仓库** 提问。
