### ISSUE TITLE
Add several domains to the list

### ISSUE THREAD

**Issue by jleaves** [v2fly/domain-list-community#830]
Please consider adding the following domains:

Add to "adobe":
- scene7.com (Adobe Dynamic Media Delivery)

Create "goodreads" and add:
- goodreads.com
- gr-assets.com

Add to "linkedin":
- lynda.com (Linkedin Learning)
- linkedin.cn (with tag `@cn`)
- licdn.cn (with tag `@cn`)

Create "apkcombo" and add:
- apkcombo.com

(Ideally, maybe creating a new category "apk-download" about all APK download sites, which includes exsiting "apkpure" and "apkmirror")

**Comment by IceCodeNew** [comment]
PR is welcome.

**Comment by rootmelo92118** [comment]
> PR is welcome.

I have a question. Do you think I need to add a category to include apk download station? The reason is it only have three download stations in this repository. If I create a new category, it will violate the policy or not?
