### ISSUE TITLE
为什么要在Microsoft中包含GitHub的数据

### ISSUE THREAD

**Issue by Iveon** [v2fly/domain-list-community#845]
这真的不是一个好主意

**Comment by IceCodeNew** [comment]
https://news.microsoft.com/announcement/microsoft-acquires-github/

**Comment by Iveon** [comment]
> https://news.microsoft.com/announcement/microsoft-acquires-github/

我没有在GitHub中发现任何他是Microsoft的子公司的信息，https://github.com/about 难道他不应该是独立运营的吗？
