### ISSUE TITLE
请问能否添加该微软域名？

### ISSUE THREAD

**Issue by IRN-Kawakaze** [v2fly/domain-list-community#864]
`svc.ms`
未在本项目里搜到该域名。

用于国际版 SharePoint Online 和 OneDrive for Business ，从 sharepoint.com 下载文件时就有可能使用到这个域名。（例如：southeastasia1-mediap.svc.ms）。

官方链接：
https://docs.microsoft.com/zh-cn/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide

如果可以的话麻烦添加一下，谢谢。

**Comment by IceCodeNew** [comment]
感谢反馈，我最迟今天晚上会处理这个问题。请耐心等待。
