### ISSUE TITLE
直连bat里有一个不能访问,怎么生成bat

### ISSUE THREAD

**Issue by 107295472** [v2fly/domain-list-community#865]
cdn.jsdelivr.net不能访问。直连里还是full:cdn.jsdelivr.net  ，我想这个也走代理怎么实现呢

**Comment by IceCodeNew** [comment]
不要在多个 issue 上反馈同一个问题。
jsdelivr在国内是否能访问我晚点会再确认一次，你先排除掉自己网络的问题。

**Comment by 107295472** [comment]
> 不要在多个 issue 上反馈同一个问题。 jsdelivr在国内是否能访问我晚点会再确认一次，你先排除掉自己网络的问题。

家里可访问，公司网不行，是移动网

**Comment by IceCodeNew** [comment]
https://github.com/jsdelivr/jsdelivr/issues/18374

@107295472
