### ISSUE TITLE
關於 #863 pull request 的操作

### ISSUE THREAD

**Issue by rootmelo92118** [v2fly/domain-list-community#867]
#863  該項pull request引用自大韓民國被封鎖的網站列表 [https://github.com/wpzzz/blocked-sites-in-south-korea/blob/main/list.txt](https://github.com/wpzzz/blocked-sites-in-south-korea/blob/main/list.txt) 該檔案內容共計1119條，該pull request加入了，依據大韓民國網路審查標準，並不是只有封鎖色情網站， 而他包含進來的資料有1072條， 這一個域名的量是非常大的很有可能會引發人們的惰性，所以我假設他只去除了與原列表相同的網站， 而將其他不屬於色情的內容包含進來， 然後我真的發現了目前我找到有三個不屬於色情內容， 而還有一些失效域名，目前我還沒有把整個列表檢查完畢而且短期之內也不太可能。需不需要對此操作進行roll back或是還原（我個人建議這麼做）， 又或者是保持現狀不變然後由人工去慢慢排查域名將不屬於本分類的域名慢慢移除。

**Comment by IceCodeNew** [comment]
慢慢排查吧，辛苦你了。
我昨晚就在担心这个问题，但可惜我查过的域名恰好都是成人网站，就漏过去了。

**Comment by rootmelo92118** [comment]
> 慢慢排查吧，辛苦你了。
> 我昨晚就在担心这个问题，但可惜我查过的域名恰好都是成人网站，就漏过去了。

我知道了，我慢慢來

**Comment by IceCodeNew** [comment]
#1655 PTAL @rootmelo92118
