### ISSUE TITLE
阿里云oss节点问题

### ISSUE THREAD

**Issue by noname01t1** [v2fly/domain-list-community#869]
阿里云oss使用aliyuncs.com域名 部分节点在海外 是不是需要部分移除geosite:cn

**Comment by noname01t1** [comment]
节点列表 https://help.aliyun.com/document_detail/31837.html
境外节点地址：
```
oss-cn-hongkong.aliyuncs.com
oss-us-west-1.aliyuncs.com
oss-us-east-1.aliyuncs.com
oss-ap-northeast-1.aliyuncs.com
oss-ap-northeast-2.aliyuncs.com
oss-ap-southeast-1.aliyuncs.com
oss-ap-southeast-2.aliyuncs.com
oss-ap-southeast-3.aliyuncs.com
oss-ap-southeast-5.aliyuncs.com
oss-ap-southeast-6.aliyuncs.com
oss-ap-southeast-7.aliyuncs.com
oss-ap-south-1.aliyuncs.com
oss-eu-central-1.aliyuncs.com
oss-eu-west-1.aliyuncs.com
oss-me-east-1.aliyuncs.com
```

**Comment by rootmelo92118** [comment]
或許可以反過來，將境內節點地址加入就好

**Comment by noname01t1** [comment]
> 或許可以反過來，將境內節點地址加入就好

我不确定反向是否方便 因为域名是在aliyun的文件中 没编辑过不太清楚

**Comment by rootmelo92118** [comment]
> > 或許可以反過來，將境內節點地址加入就好
> 
> 我不确定反向是否方便 因为域名是在aliyun的文件中 没编辑过不太清楚



我的意見是將以下域名加入即可

`
oss-cn-hangzhou.aliyuncs.com
oss-cn-shanghai.aliyuncs.com
oss-cn-nanjing.aliyuncs.com
oss-cn-qingdao.aliyuncs.com
oss-cn-beijing.aliyuncs.com
oss-cn-zhangjiakou.aliyuncs.com
oss-cn-huhehaote.aliyuncs.com
oss-cn-wulanchabu.aliyuncs.com
oss-cn-shenzhen.aliyuncs.com
oss-cn-heyuan.aliyuncs.com
oss-cn-guangzhou.aliyuncs.com
oss-cn-chengdu.aliyuncs.com
`

**Comment by IceCodeNew** [comment]
我确认一下，是希望将下面这一行改成更精细的，只包括国内节点的部分是吗？
https://github.com/v2fly/domain-list-community/blob/07baef10e20c1f02089bdac5ff78e6d60a2c292f/data/aliyun#L10 

粗略看了一眼目前 aliyun 没有专门划分出海外节点归档的文件来，这部分可能要仔细确认过后另外开新的分类。（至少放到 alibabacloud 看起来不合适）

**Comment by rootmelo92118** [comment]
> 我确认一下，是希望将下面这一行改成更精细的，只包括国内节点的部分是吗？
> 
> https://github.com/v2fly/domain-list-community/blob/07baef10e20c1f02089bdac5ff78e6d60a2c292f/data/aliyun#L10
> 
> 粗略看了一眼目前 aliyun 没有专门划分出海外节点归档的文件来，这部分可能要仔细确认过后另外开新的分类。（至少放到 alibabacloud 看起来不合适）

我有一個想法，比照#831的方式處理

**Comment by IceCodeNew** [comment]
> 我有一個想法，比照 #831 的方式處理，但是依照具體情況，這將是一個不算小的修正過程

我没有意见，你如果有兴趣的话可以在空闲时间慢慢做这个。感谢投入时间精力。

**Comment by rootmelo92118** [comment]
> > 我有一個想法，比照 #831 的方式處理，但是依照具體情況，這將是一個不算小的修正過程
> 
> 我没有意见，你如果有兴趣的话可以在空闲时间慢慢做这个。感谢投入时间精力。

我研究了一下，很多的域名本身並不固定（尤其是CDN）有可能隨時隨地都有新的域名產生，搜索全部域名並進行單獨歸類並不現實，如果硬去分也有會有為數不少的漏網之魚。

不如先依照本issue的部分排除已被發現不屬於該分類的域名，至於其他的部分，就等未來其他使用者回報後再處理。

**Comment by rootmelo92118** [comment]
好我剛剛試過了，用戶提出異議的域名cn/geolocation-cn/alibaba/aliyun中，aliyun被包含在alibaba中並以該分類加入geolocation-cn中，除非拆除整個alibaba讓裡面的分類與域名個別單獨引入geolocation-cn或是加入新語法（例如：exclude）否則依照顯有結構下，不太可能將這些域名單獨分離出來（即使使用@cn也不合適）。

**Comment by IceCodeNew** [comment]
> 我研究了一下，很多的域名本身並不固定（尤其是CDN）有可能隨時隨地都有新的域名產生，搜索全部域名並進行單獨歸類並不現實，如果硬去分也有會有為數不少的漏網之魚。

不必苛求一次 PR 就做完美，有漏网之鱼可以不断在之后补充。
另外，通过正则表达式去匹配也是个不错的手段。

**Comment by rootmelo92118** [comment]
> > 我研究了一下，很多的域名本身並不固定（尤其是CDN）有可能隨時隨地都有新的域名產生，搜索全部域名並進行單獨歸類並不現實，如果硬去分也有會有為數不少的漏網之魚。
> 
> 不必苛求一次 PR 就做完美，有漏网之鱼可以不断在之后补充。 另外，通过正则表达式去匹配也是个不错的手段。

依照現在被引入的結構，這個要求很難被達成，因為被包含在geolocation-cn的是alibaba，而不是aliyun，而僅將大陸境內域名包含在alibaba中也有違該分類的定義，因為境外域名依然屬於阿里巴巴所有，這個定義並沒有改變。所以單獨將境外域名抽離出來可能會導致連動好幾個分類也得拆分，使得從屬關係複雜化，又或者拆分aliyun本身可能也要將alibaba本身拆分為大陸與境外。我個人的想法是，如果這個問題沒有影響到一般使用者使用，那可能就先這樣放著，如果有，再進行這項大型工程。
因為不完整的pull request所導致的分流問題，有可能會造成使用者的麻煩或者導致使用者的帳號被官方判定異常連線，進而導致被封控甚至封號的可能。



還有使用正則表達式匹配域名的方法，阿里雲cdn的子域名命名規則與地域並沒有接聯繫，所以只使用正則表達式去匹配域名也很難從中分揀出在大陸境內的域名。

**Comment by IceCodeNew** [comment]
> 依照現在被引入的結構，這個要求很難被達成，因為被包含在geolocation-cn的是alibaba，而不是aliyun，而僅將大陸境內域名包含在alibaba中也有違該分類的定義，因為境外域名依然屬於阿里巴巴所有，這個定義並沒有改變。所以單獨將境外域名抽離出來可能會導致連動好幾個分類也得拆分，使得從屬關係複雜化，又或者拆分aliyun本身可能也要將alibaba本身拆分為大陸與境外。我個人的想法是，如果這個問題沒有影響到一般使用者使用，那可能就先這樣放著，如果有，再進行這項大型工程。 因為不完整的pull request所導致的分流問題，有可能會造成使用者的麻煩或者導致使用者的帳號被官方判定異常連線，進而導致被封控甚至封號的可能。
> 
> 還有使用正則表達式匹配域名的方法，阿里雲cdn的子域名命名規則與地域並沒有接聯繫，所以只使用正則表達式去匹配域名也很難從中分揀出在大陸境內的域名。

基本上我觉得只要用好 `@!cn` 属性就可以了。这个项目因为没有合并 #255 (Issue 讨论可参见 #256 ) 所以不能输出方便使用的结果。
但是下游项目 https://github.com/Loyalsoldier/domain-list-custom 能解决这个问题。而从列表整理的角度出发，我完全支持把阿里云的域名按照 `@cn` 和 `@!cn` 两种属性进行拆分。

**Comment by rootmelo92118** [comment]
> > 依照現在被引入的結構，這個要求很難被達成，因為被包含在geolocation-cn的是alibaba，而不是aliyun，而僅將大陸境內域名包含在alibaba中也有違該分類的定義，因為境外域名依然屬於阿里巴巴所有，這個定義並沒有改變。所以單獨將境外域名抽離出來可能會導致連動好幾個分類也得拆分，使得從屬關係複雜化，又或者拆分aliyun本身可能也要將alibaba本身拆分為大陸與境外。我個人的想法是，如果這個問題沒有影響到一般使用者使用，那可能就先這樣放著，如果有，再進行這項大型工程。 因為不完整的pull request所導致的分流問題，有可能會造成使用者的麻煩或者導致使用者的帳號被官方判定異常連線，進而導致被封控甚至封號的可能。
> > 還有使用正則表達式匹配域名的方法，阿里雲cdn的子域名命名規則與地域並沒有接聯繫，所以只使用正則表達式去匹配域名也很難從中分揀出在大陸境內的域名。
> 
> 基本上我觉得只要用好 `@!cn` 属性就可以了。这个项目因为没有合并 #255 (Issue 讨论可参见 #256 ) 所以不能输出方便使用的结果。 但是下游项目 https://github.com/Loyalsoldier/domain-list-custom 能解决这个问题。而从列表整理的角度出发，我完全支持把阿里云的域名按照 `@cn` 和 `@!cn` 两种属性进行拆分。

include 可以使用`@cn`或`@!cn`的語法嗎？

**Comment by IceCodeNew** [comment]
> include 可以使用`@cn`或`@!cn`的語法嗎？

`@cn`或`@!cn` 属性是对于单条域名来说的，include 条目后面带类似 `@cn` 属性的功能应该还没有实现。
你只需要在每条拆分出来的域名后添加正确的属性即可。https://github.com/Loyalsoldier/domain-list-custom 项目能够处理好之后的问题

**Comment by rootmelo92118** [comment]
> 

你的意思是那個專案可以自行分揀在geolocation-cn中include的類別裡僅包含@cn的域名？

**Comment by rootmelo92118** [comment]
> > include 可以使用`@cn`或`@!cn`的語法嗎？
> 
> `@cn`或`@!cn` 属性是对于单条域名来说的，include 条目后面带类似 `@cn` 属性的功能应该还没有实现。 你只需要在每条拆分出来的域名后添加正确的属性即可。https://github.com/Loyalsoldier/domain-list-custom 项目能够处理好之后的问题

你的意思是那個專案可以自行分揀在geolocation-cn中include的類別裡僅包含https://github.com/cn的域名？

**Comment by IceCodeNew** [comment]
> > > include 可以使用`@cn`或`@!cn`的語法嗎？
> > 
> > 
> > `@cn`或`@!cn` 属性是对于单条域名来说的，include 条目后面带类似 `@cn` 属性的功能应该还没有实现。 你只需要在每条拆分出来的域名后添加正确的属性即可。[Loyalsoldier/domain-list-custom](https://github.com/Loyalsoldier/domain-list-custom) 项目能够处理好之后的问题
> 
> 你的意思是那個專案可以自行分揀在geolocation-cn中include的類別裡僅包含`@cn`的域名？

没看懂，你可以参考下项目的 README

**Comment by rootmelo92118** [comment]
> > > > include 可以使用`@cn`或`@!cn`的語法嗎？
> > > 
> > > 
> > > `@cn`或`@!cn` 属性是对于单条域名来说的，include 条目后面带类似 `@cn` 属性的功能应该还没有实现。 你只需要在每条拆分出来的域名后添加正确的属性即可。[Loyalsoldier/domain-list-custom](https://github.com/Loyalsoldier/domain-list-custom) 项目能够处理好之后的问题
> > 
> > 
> > 你的意思是那個專案可以自行分揀在geolocation-cn中include的類別裡僅包含`@cn`的域名？
> 
> 没看懂，你可以参考下项目的 README

沒事了
