### ISSUE TITLE
fonts.googleapis.com 被归类为大陆域名

### ISSUE THREAD

**Issue by lfod1997** [v2fly/domain-list-community#880]
不清楚是贵项目还是 V2RayN 的原因，googleapis.com 被归类为大陆域名；但在不通过代理时，ping googleapis.com 全部超时。

**问题：** 至少可以确定 fonts.googleapis.com 被归类为 `geosite:cn`，但不包含在 `geolocation-cn` 和 `tld-cn` 中。

**复现：** V2RayN 中，在全局 proxy 的基础上，建立路由规则 `geosite:geolocation-cn, geosite:tld-cn` → direct，则 fonts.googleapis.com 能够按 proxy 代理；换为规则 `geosite:cn` → direct，则 fonts.googleapis.com 按 direct 代理。

**系统信息：** Win10 19042, v2rayN V5.16, Xray 1.5.4 Custom (go1.17.7 windows/386), geofile 更新于今日, China Telecom

**Comment by IceCodeNew** [comment]
<img width="860" alt="image" src="https://user-images.githubusercontent.com/32576256/167571481-a6b15bb9-d101-421b-bddc-cceebfb4bda3.png">

搜索一下不就知道是不是这个项目的问题了吗？
如果你本地的 geosite 文件已经是最新的，那就是第三方项目的问题。

**Comment by IceCodeNew** [comment]
https://github.com/v2fly/domain-list-community/blob/cde444565527ab838306156dfbfe45e69019c93c/data/google#L556

**Comment by IceCodeNew** [comment]
https://www.boce.com/http/731ed763ab7260d495f79b392eea3f04.html

这应该是你的网络环境问题。不会考虑为个别特例删除掉 `fonts.googleapis.com` 域名的 `@cn` 记录
