### ISSUE TITLE
cdn.jsdelivr.net静态资源cdn不行了

### ISSUE THREAD

**Issue by xubanxian233** [v2fly/domain-list-community#891]
cdn.jsdelivr.net静态资源cdn不行了，国内访问不了

**Comment by IceCodeNew** [comment]
https://www.boce.com/http/9bc5bd34385f6c42719faec6d2244b53.html?k=4FF0zKTMjn

我不反对取消 `cdn.jsdelivr.net` 的 `@cn` 属性。有空的话可以提交 PR。我白天忙不过来。
