### ISSUE TITLE
反向匹配不生效

### ISSUE THREAD

**Issue by alfredtofu** [v2fly/domain-list-community#894]
我定义了一个文件tttt，里面定义了是我想走代理的域名，然后所有不在这个文件里面的域名应该block，我定义了路由
```
      {
        "type": "field",
        "outboundTag": "block",
        "domain": [
          "ext:dlc.dat:!tttt"
        ]
      }
```
`dlc.dat`是我生成包含tttt文件的资源文件，运行的时候报错：
```
Failed to start: main/commands: failed to load config: [client.json] > infra/conf/rule: invalid field rule > infra/conf/rule: failed to parse domain rule: ext:dlc.dat:!tttt > infra/conf/rule: failed to load external geosite: !tttt from dlc.dat > infra/conf/geodata/standard: list not found in dlc.dat: !tttt
```

请问该怎么做反向匹配？

**Comment by AkinoKaede** [comment]
v2fly/v2ray-core#1793

**Comment by rootmelo92118** [comment]
> 我定义了一个文件tttt，里面定义了是我想走代理的域名，然后所有不在这个文件里面的域名应该block，我定义了路由
> 
> ```
>       {
>         "type": "field",
>         "outboundTag": "block",
>         "domain": [
>           "ext:dlc.dat:!tttt"
>         ]
>       }
> ```
> 
> `dlc.dat`是我生成包含tttt文件的资源文件，运行的时候报错：
> 
> ```
> Failed to start: main/commands: failed to load config: [client.json] > infra/conf/rule: invalid field rule > infra/conf/rule: failed to parse domain rule: ext:dlc.dat:!tttt > infra/conf/rule: failed to load external geosite: !tttt from dlc.dat > infra/conf/geodata/standard: list not found in dlc.dat: !tttt
> ```
> 
> 请问该怎么做反向匹配？

我個人的建議是，將tttt設定為direct，而其他域名設定為block

```
    "rules": [
      //這個區塊是你的域名，就是外處理的部分。
      {
        "type": "field",
        "domain": [
          "ext:dlc.dat:tttt"
        ],
        "outboundTag": "direct"
      },
      //這個區塊是其他域名預設的處理方式，在這裡是全部封鎖。
      {
        "type": "field",
        "network": "tcp,udp",
        "outboundTag": "block"
      }
    ]
```
