### ISSUE TITLE
[Discuss] About new category `geolocation-global`(Temp name)

### ISSUE THREAD

**Issue by akiirui** [v2fly/domain-list-community#91]
由于之前有用户提出了[部分Google服务大陆可直连，DLC中能否区别开来？ #487](http://github.com/v2ray/domain-list-community/issues/487), 于是才有了本次的讨论.

由于主要讨论内容所在的 PR https://github.com/v2fly/domain-list-community/pull/88 已合并, 于是单独开一个 Issues 进行相关讨论.

以下内容仅为个人提出的意见, 大家可以提出意见进行修改.

> 1. 更改`geolocation-!cn`的定义为“在中国大陆外拥有连接点的域名列表”
> 2. `@cn`定义为“在中国大陆拥有连接点的境外域名”，用于`geolocation-!cn`及其包含的子列表，建立`geolocation-global`收集这类域名
> 3. `@!cn`定义为“在中国大陆外拥有连接点的境内域名”，用于`geolocation-cn`及其包含的子列表，同样收集于`geolocation-global`（我猜测，需要用到此类域名的用户较少，标记工作可以延后）
> 4. 新增`include:list@attr`这种包含方式

<a id="category-definition"></a>
把这几条综合简化一下, 可以将其拆分为 3 个大分类

1. `geolocation-cn`: 中国大陆公司所属的域名列表
2. `geolocation-!cn`: 境外公司所属的域名列表
3. `geolocation-global`<sup>暂命名</sup>: 在中国大陆与其境外均有可用连接点的的域名列表
    - 主要包含模棱两可的域名, 例如中国公司所属但对境外提供主要服务的域名, 或境外公司所属但在中国有可用连接点的域名
    - 其中境外公司所属但在中国有可用连接点的域名, 标记为 `@cn`<sup>待定</sup>
    - 其中中国公司所属但对境外提供主要服务的域名, 标记为 `@!cn`<sup>待定</sup>

这样就可以同时满足境内境外的用户需求, 用户可以自行选择 `geolocation-global[@cn|@!cn]` 直连或代理.

现在的可用方式为:

1. 中国用户, **仅代理**中国大陆外的公司所属的域名列表:
```
CN User -> (Optional)(Direct global) -> CN
           (Optional)(Proxy  global) -> Outside
                     (Proxy     !cn) -> Outside
                     (Direct    all) -> CN
```

2. 中国用户, **代理**中国大陆内的公司所属的域名列表**以外的域名**:
```
CN User -> (Optional)(Direct global) -> CN
           (Optional)(Proxy  global) -> Outside
                     (Direct     cn) -> CN
                     (Proxy     all) -> Outside
```

3. 境外用户, **仅代理**中国大陆内的公司所属的域名列表:
```
!CN User -> (Optional)(Direct global) -> Outside
            (Optional)(Proxy  global) -> CN         #这个完全没有必要
                      (Proxy      cn) -> CN
                      (Direct    all) -> Outside
```

^: 由于 v2ray 的 routing rules 优先级的关系.只要使用了 `global` 的 rules 在 `!cn` 前面, 即使 `global` 内的域名被 `!cn` 包含了也没关系.

---

执行方式大概如下:

1. 以上面的3个[分类定义](#category-definition)整理 `geolocaion-cn` 和 `geolocation-!cn` 中包含的域名.
    - 其确定的分类定义可以再慢慢进行讨论
2. 整理在中国大陆与其境外均有可用连接点的域名列表至 `<company-name>-global`.
    - 可参考 [#89](https://github.com/v2fly/domain-list-community/pull/89) 
    - 也可以不创建 `<company-name>-global` 而在其原本 `<company-name>` 中以 `@attr` 实现
3. 创建新的大分类 `geolocation-global`<sup>暂命名</sup>, 整合所有 `<company-name>-attr`.
    - 如使用 `@attr` 实现则可以 `include:<company-name>@attr`

以上的方式工程量会比较少, 只需要为相关的条目添加 `@attr` 即可.

---

> 部分列表末尾放置有CDN，其域名不一定属于列表的实体。以上方案并未考虑这种特殊情况，但个人认为可以采取相同手段

如果其 CDN 同时提供境内境外接入点那么按照上面的可以直接添加 `@global`

> 标记流程是否能自动化？例如 #54 中提及的域名校验功能

可行, 可以分析**境外公司所属域名**解析到的 IP 结果, 如果中国大陆 DNS 返回的 IP 在 `geoip:cn` 内就可以为其标记 `@global`

> geolocation-global名称是否合适？如果合适，是否要将@cn及@!cn合并为@global？

命名方面, 以我上面的[分类定义](#category-definition)来说, 包含的域名是来自境外公司所属但在中国有可用接入点的域名.  
其实用 `geolocation-cn-available` 比较合适, 不过太长了...  
参考 `!cn` 可以简化为 `geolocation-&cn` 或者 `~cn` 之类的可能比较好.

> 在有@cn、@!cn的情况下，如果新增@dl来标记系统、软件、游戏的下载、更新域名，还有意义吗？

`@dl` 应该用处不大, 境内用户下载境外内容如果不经过代理速度极慢几乎不可用.  
而下载境内的内容由于 `geolocaion-cn` 直接直连也不需要 `@dl`.

---

Jul 29, 16:00. 补充遗漏, 且按下文修改上文的部分内容.

`geolocation-global`<sup>暂命名</sup> 里也应该分两小类:

- 中国大陆公司所属但对境外提供主要服务的域名, 标记 `@!cn`<sup>待定</sup>
    - 例 `data/alibabacloud`
- 境外公司所属但在中国大陆有可用连接点的域名, 标记 `@cn`<sup>待定</sup>
    - 例 `full:fonts.googleapi.com` 

当前某些域名被 `geolocation-cn` 和 `geolocation-!cn` 同时包含, 例:

```
geolocation-cn  <- include:alibaba <- include:alibabacloud
geolocation-!cn <- include:alibabacloud
```

新的类别 `geolocation-global`<sup>暂定</sup> 目的就是解决这些**模棱两可**的规则冲突.  
同样以 `alibabacloud` 为例.  
从 `alibaba` 中删除 `alibabacloud`,  
为 `alibabacloud` 内的域名标记 `@!cn`,  
为 `geolocation-global` 添加 `alibabacloud`

```
geolocation-cn     <- include:alibaba
geolocation-!cn    <- include:alibabacloud
geolocation-global <- include:alibabacloud
```

这样就解决了冲突, 且用户可用以 `geolocaion-global@!cn` 覆盖 `cn` 或 `!cn` 选择直连或者代理相关域名.  
而不是由于重复的归属于 `cn` 和 `!cn` 导致意外发生.

**Comment by kslr** [comment]
我觉得保持足够简单可能比较好，忽略 某些域 在国内有CDN这些需求。
另外可以建立一个属于cdn厂商的列表，再深入的让用户单独添加这些路由。

**Comment by akiirui** [comment]
> 我觉得保持足够简单可能比较好，忽略 某些域 在国内有CDN这些需求。
> 可以建立一个单独属于cdn厂商的列表，再深入的让用户单独添加这些路由。
> （ 头有点晕，等到晚上看正文

我一开始也是这么想的...
但是自从 https://github.com/v2ray/domain-list-community/issues/487 有用户提出了这个问题之后.
新添加的规则 https://github.com/v2fly/domain-list-community/commit/0971cd48ad85bb13975ff8e4f6a6ccc8911939fa 影响到了我的使用. 于是就想既然都添加进来了, 那就把它规范化...
最终还是看讨论结果, 这里只是一个如何规范化相关域名列表的讨论~

**Comment by Robot-DaneelOlivaw** [comment]
补充一下讨论背景：

现在希望解决的问题是，部分域名在中国大陆境内外均有连接点，但其属于境外企业或组织、包含在`geolocation-!cn`中，所以没办法进行单独处理。日前 #79 修复了标签功能，允许使用`@attr`对这类域名进行标记，因此可以开始讨论出一个具体解决方案了。

目前希望使用`@cn`对`geolocation-!cn`及其包含子列表中的域名进行标记，并整理成一个单独的列表`geolocation-global`。

`@!cn`则完全相反，用于标记中国大陆境内外都有连接点、但属于境内企业或组织的域名，主要服务境外用户。

**Comment by Loyalsoldier** [comment]
我先尝试阅读 V2Ray DNS 部分的源码，看看能不能找出规则处理的优先级的 bug。找到的话，先修优先级 bug，这样通过 DNS 配置就可以避免用 V2Ray 做网关当透明代理时的解析问题。

**Comment by kslr** [comment]
> 我先尝试阅读 V2Ray DNS 部分的源码，看看能不能找出规则处理的优先级的 bug。找到的话，先修优先级 bug，这样通过 DNS 配置就可以避免用 V2Ray 做网关当透明代理时的解析问题。

这个是什么

**Comment by Loyalsoldier** [comment]
> > 我先尝试阅读 V2Ray DNS 部分的源码，看看能不能找出规则处理的优先级的 bug。找到的话，先修优先级 bug，这样通过 DNS 配置就可以避免用 V2Ray 做网关当透明代理时的解析问题。
> 
> 这个是什么

```
"dns": {
  "servers": [
    {
      "address": "https+local://dns.alidns.com/dns-query",
      "domains": [
        "geosite:cn",
        "geosite:google@cn",
        "full:fonts.googleapis.com"
      ]
    },
    {
      "address": "https://1.1.1.1/dns-query",
      "domains": [
        "geosite:geolocation-!cn"
      ]
    },
    "223.5.5.5"
  ]
}
```

由于现在域名 `font.googleapis.com` 同时在 `google@cn` 和 `geolocation-!cn` 中。

当 V2Ray 做网关或者透明代理时，使用上面这样的 DNS 配置，解析 `font.googleapis.com` 会大概率使用 `1.1.1.1`，极小概率使用 `dns.alidns.com`。

**Comment by Robot-DaneelOlivaw** [comment]
> `geolocation-global`<sup>暂命名</sup> 里也应该分两小类:
> - 中国大陆公司所属但对境外提供主要服务的域名, 标记 `@!cn`<sup>待定</sup>
> - 境外公司所属但在中国大陆有可用连接点的域名, 标记 `@cn`<sup>待定</sup>

根据文档，生成文件时会将`include:`替换为列表的真实内容：

> 2. Replace include: lines with the actual content of the file.

那如果实现了`include:list@attr`这一功能，子列表中的标签也应该会被继承下来，即`geolocation-global`会有标记好的`@cn`和`@!cn`，那这两小类就自然分类完成，可以用您提及的`geolocation-global[@cn|@!cn]`来表示。

> 同样以 `alibabacloud` 为例.  
> 从 `alibaba` 中删除 `alibabacloud`,  
> 为 `alibabacloud` 内的域名标记 `@!cn`,  
> 为 `geolocation-global` 添加 `alibabacloud`
>
> 用户可用以 `geolocaion-global@!cn` 覆盖 `cn` 或 `!cn` 选择直连或者代理相关域名.

既然可以用`geolocaion-global@!cn`进行覆盖，那就没有必要从`alibaba`中删除`alibabacloud`了。除此之外我认为您这一方案是比较优雅的。

**Comment by Robot-DaneelOlivaw** [comment]
> 当 V2Ray 做网关或者透明代理时，使用上面这样的 DNS 配置，解析 `font.googleapis.com` 会大概率使用 `1.1.1.1`，当这个解析失败，才会使用 `dns.alidns.com`

观察了一下，V2Ray会选择符合规则的最后一个DNS。

**Comment by Loyalsoldier** [comment]
> 观察了一下，V2Ray会选择符合规则的最后一个DNS。

你不说我还没发现，测试了一下，好像还真是这样。但是我昨天看了代码，并没有发现这个规则 😓

**Comment by akiirui** [comment]
截至此回复为止, 各位都提出了几点不同的意见, 其中与本主题冲突的几点:

- 不应迁就路由规则而删除某些应该存在的域名，如 alibabacloud 的确属于 alibaba，那后者就应包含前者

这个是我考虑不周, 不应该迁就 `global` 删改其他规则.

例子在这里引用得可能不太恰当, 但的确应该修改.  
(因为这是整个列表里唯一一个同时 `include:` 在 `cn` 和 `!cn` 中的一个域名列表)  
不过这个问题属于 https://github.com/v2fly/domain-list-community/issues/28 所讨论的范围, 这里就不讨论这个问题了.

- 至于列表名称，新增的这一列表是 geolocation-cn 与 geolocation-!cn 并集的子集，仍可以称作 geolocation.

至于这个新列表的名称, `global` 意为 `全球`, 而这个列表主要包含的是:

- `!cn` 中, 境外公司所属但在中国大陆有可用接入点的的域名
- `cn` 中, 中国公司所属但对境外提供主要服务的域名

使用 `global` 就有点不太贴切, 且:

- 目前应该先着眼处理@cn（仅考虑境内用户的使用场景）

我们是否可以在此新列表中完全忽略 `@!cn`, 将这个列表的用户限定为境内用户. 如果这样, 名称就可以命名为 `with-cn`

---

又或者不创建这个新的列表, 仅在其主体列表内为相关的域名添加 `@cn` 然后让有需求的用户使用 `geosite:list@cn` 或 `geosite:list@!cn`:

```
data/geolocation-!cn:
    include:adidas
        adidas.com.cn @cn
        ...
    include:google
        full:fonts.googleapi.com @cn
        ...
    ...

data/geolcation-cn:
    include:alibaba
        include:alibabacloud
            alicloud.com @!cn
            ...
        ...
    ...
```

```json
{
  "type": "field",
  "outboundTag": "direct",
  "domain": [
    "geosite:geolocation-cn",
    "geosite:geolocation-!cn@cn"
  ]
},
{
  "type": "field",
  "outboundTag": "proxy",
  "domain": [
    "geosite:geolocation-!cn",
    "geosite:geolocation-cn@!cn",
  ]
}
```

这样既保持了简单性, 让用户了解这条规则的含义. 也不需要修改 `main.go` 新增 `include:list@attr` 包含方式.

^注: 上面用到包含到的 `alibabacloud` 在均包含在 `cn` 和 `!cn`, 这个冲突需要解决.

**Comment by Robot-DaneelOlivaw** [comment]
> 这样既保持了简单性, 让用户了解这条规则的含义. 也不需要修改`main.go`新增`include:list@attr`包含方式.

这个想法提醒了我，在子列表中标记`@cn`并且包含在`geolocation-!cn`中，生成文件时域名就已经拥有标签。经测试，`geosite:geolocation-!cn@cn`是包含这类域名的。那工作就可以进一步简化，只需添加`@cn`，而无需建立`geolocation-global`、也无需新增`include:list@attr`了。

> ^注: 上面用例子中的 alibabacloud 均包含在 cn 和 !cn, 这个冲突需要解决.

为`alibabacloud`标记`@!cn`，在路由规则中优先级较高处进行特殊处理或许可以解决问题？


> 甚至可用更简单化一点, 一切保持原样, 不添加`@attr`, 为其创建一个新列表

我担心若要为所有在中国大陆拥有连接点的境外企业/组织建立列表，数量会过多。另外`@attr`的好处是可继承，例如在`alibabacloud`中标记了`@!cn`，可以从`geosite:geolocation-cn@!cn`、`geosite:alibaba@!cn`、`geosite:alibabacloud@!cn`三个层级对这些域名进行路由规则配置。

**Comment by akiirui** [comment]
由于已经以讨论内容对新增内容作出了修改, 此讨论应该可以关闭了.
