### ISSUE TITLE
Consider moving `ibytedtos.com` from `bytedance` to `tiktok`?

### ISSUE THREAD

**Issue by dyhkwong** [v2fly/domain-list-community#926]
this seems to be something like CDN when you visit `www.tiktok.com`, and not used by other bytedance services.
https://urlscan.io/domain/ibytedtos.com
https://urlscan.io/search/#domain:%22ibytedtos.com%22

**Comment by IceCodeNew** [comment]
@Loyalsoldier https://github.com/v2fly/domain-list-community/blame/4bc6098ff4333a5fb284422df24883aa5960e855/data/bytedance#L23

**Comment by rootmelo92118** [comment]
@dyhkwong I think you can add `geosite:bytedance@!cn` and `geosite:tiktok` into your routing rule to solve the problem.

**Comment by rootmelo92118** [comment]
> yea in fact this did not cause any issues for me and routing issues can always be solved by adding some routing rules. Just talking about domain classification itself.

Ok.
