### ISSUE TITLE
google 中的 googleapis.cn 走直连会导致 Google Play Store 无法下载更新应用

### ISSUE THREAD

**Issue by DustinWin** [v2fly/domain-list-community#944]
感谢 @eastarpen 定位出了问题所在，原地址：https://github.com/Loyalsoldier/clash-rules/issues/95
Q: 为什么我的 Google Play Services 无法连接 / 为什么我的 Google Play 无法登录，提示错误 DF-DFERH-01 / 我的日志里面 googleapis.cn 走的是直连 DIRECT。
A: 部分国产 ROM 连接 Google Play Services 使用的是 googleapis.cn ，而不是 googleapis.com 。无法连接的一个可能的原因是 googleapis.cn 的规则匹配问题，它优先匹配了CN字段，导致走的直连。

**问题：**
在 data 文件夹的 google 规则中，有一行如下：
`googleapis.cn @cn`
该地址走直连会导致 Google Play Store 无法下载更新应用，希望修改一下，感谢！

**Comment by IceCodeNew** [comment]
DNS 重写是最好的处理办法，`googleapis.cn` 直连是为了解决其他服务的问题。
要用 google play 需要直接避免使用 `googleapis.cn`，因为它还会被 `.cn` 规则匹配到。
