### ISSUE TITLE
申請repo maintainer權限

### ISSUE THREAD

**Issue by rootmelo92118** [v2fly/domain-list-community#954]
經歷過目前68次的commit，發現了部分問題(#867)，以及解決了部分用戶的回報問題(#891、#894、#944)，以及幫助部分用戶提交pull request。
我認為我有能力參與維護與管理本儲存庫的工作。

All the best,
rootmelo92118

**Comment by IceCodeNew** [comment]
支持。不过以后自己提 PR 不建议自己推合并，还是要留给别人 review 的时间哦~

**Comment by rootmelo92118** [comment]
> 支持。不过以后自己提 PR 不建议自己推合并，还是要留给别人 review 的时间哦~

沒有問題

**Comment by kslr** [comment]
感谢各位的工作，没有比你们更合适成为维护者的了。
