### ISSUE TITLE
有没有可能 以CN IP Range 替代 庞大的domain list, 来实现国内国外dns分别解析?

### ISSUE THREAD

**Issue by os9sur** [v2fly/domain-list-community#960]
如题
分给各国的 IP段列表  变动的频率非常低, 但域名变动频率非常高, 需要经常维护, 数据量还很大 比较繁琐.
所以 能否实现 类似于以下这种的 维护ip段的办法 来实现 当访问国内/国外网址时 分别走不同的 dns解析?
https://github.com/breakwa11/gfw_whitelist

**Comment by rootmelo92118** [comment]
`geoip:cn`或許可以滿足你的需求
